### ISSUE TITLE
SMS notifications

### ISSUE THREAD

**Issue by torkil** [dotkom/onlineweb4#1]
Hoiio is cheap, supports sender rebranding, sending in bulk and have an API that is not terrible.

Example request: https://secure.hoiio.com/open/sms/send?dest=%2B4791916350&msg=Hoiio+World&access_token=key&app_id=id

Each SMS sent costs USD 3.5 cents which is roughly equivalent to 20 øre.

**Comment by hernil** [comment]
I'm going to go ahead and reopen this for consideration. This might be worth a look https://django-twilio.readthedocs.org/en/latest/

**Comment by sklirg** [comment]
I'll have a look at this and come up with some thoughts and figures for next meeting.

**Comment by hernil** [comment]
@torkil might have an update on what they use at Hoopla?

**Comment by torkil** [comment]
We use PSWinCom. Pretty happy with them.

HTTP API: https://wiki.pswin.com/Gateway%20HTTP%20API.ashx

The also have SMTP API if you'd like to not worry about queuing and retrying.

**Comment by OptimusCrime** [comment]
I've used Twilio earlier. Super easy, cheap and nice. My 5 cents.

**Comment by plusk** [comment]
Not happening anytime soon, but we're open to talking about it again in the future if requested.
