### ISSUE TITLE
(Dashboard) Refactor how the list of included apps is managed

### ISSUE THREAD

**Issue by melwil** [dotkom/onlineweb4#1068]
Preferably, this should be dynamically generated from content discovered inside each app. The reasoning for this is that any app should be as loosely tied to the project that if you removed it from INSTALLED_APPS, it would not break the project.

Currently the list is statically build in dashboard_base.html, which is too rigid for the fluent setup of django otherwise.

A suggestion for how we could do this would be to have each app export a data structure of how it wants its links to appear in the list.

Suggested structure:

``` python
{ 
    'top': ('fa-wheelchair blue', _('Arrangement'), reverse('dashboard_event_index'),
    'badge': 10, # Will show a badge with 10
    'warning': True/False, # Will show a warning (optional)    
    'sublinks': [
        ('Adgangsregler', reverse('dashboard_rule_bundles'),
        ('Opprett', reverse('dashboard_create_event'),
    ],
}
```

These need to be aggregated somewhere.
- In the global urls.py, where url's in general are aggregated? 
- In apps/dashboard/tools where we generate get_base_context( )

**Comment by plusk** [comment]
We've talked about this now, and this sounds like far more hassle than it's worth. We actually like manually defining this.
