### ISSUE TITLE
Archive doesn't remember filter settings when returning to page

### ISSUE THREAD

**Issue by duvholt** [dotkom/onlineweb4#1074]
I understand why it works like this since everything is done in JavaScript, but I find this behavior pretty annoying.

A possible fix would be to implement querystrings for the filters and use pushState/replaceState to modify it in JavaScript.

**Comment by plusk** [comment]
This seems like a frontend issue. Since we're rewriting the frontend entirely in a different repository, we'll just make sure not to introduce the same problem there.
