### ISSUE TITLE
Events with several companies tied to them and no event image breaks carousel in events archive

### ISSUE THREAD

**Issue by duvholt** [dotkom/onlineweb4#1160]
![](http://i.imgur.com/E2UiTim.png)

https://github.com/dotKom/onlineweb4/blob/develop/files/static/js/EventWidget.js#L97

All company thumbnails will be marked as active which makes them all show. 
This should be changed to only mark the first one as active.

**Comment by OptimusCrime** [comment]
Is this fixed?

**Comment by sardred** [comment]
@OptimusCrime: I did you the favor of checking prod. No, it's not fixed.

**Comment by nornes** [comment]
It is fixed in the frontpage-react branch though. But the problem will remain in the events archive pave
