### ISSUE TITLE
ResourceCenter needs an update

### ISSUE THREAD

**Issue by michaeljohansen** [dotKom/onlineweb4#1166]
- Replace IRC with Slack (incl. thumbnail).
- Rename "student resources" to "Links" or "Links we like", all the resources are student resources.
- Remove link to Samfundet in "Student resources", no one needs a link to find Samfundet.
- Are the game servers alive and active? Otherwise I suggest removal.
- Under "Infosider", the link kalvskinnet.no is dead, perhaps look into renewing that domain, especially now that HiST Kalvskinnet has become a new NTNU campus.
- Remove the link to Notifier's wiki page, that information has been moved into appKom's wiki.

**Comment by hernil** [comment]
Fixed in https://github.com/dotKom/onlineweb4/pull/1387
