### ISSUE TITLE
Dashboard approvals could have som more detailed information

### ISSUE THREAD

**Issue by melwil** [dotkom/onlineweb4#1173]
Today we have no information about the user that is applying except their name and possibly what they are applying to.

Possible data which could be displayed in a drop down style manner like what happens when you press "avslå" today, could include:
- previous applications
- current field of study
- when they started on informatics

By no means limited to this, think about any information related to applicants which could assist a person tending to the applications.

**Comment by sklirg** [comment]
Look into https://github.com/dotkom/onlineweb4/issues/1418 as well.

**Comment by plusk** [comment]
It seems like parts of this issue has been implemented in the four years since it was opened. The remainders can be considered when we get around to making a new dashboard for the new frontend.
