### ISSUE TITLE
(Approval) If user has a membershipapproval pending and the ntnu-ussername is deleted it fails

### ISSUE THREAD

**Issue by melwil** [dotkom/onlineweb4#1184]
If users for some reason can make an application, but in the meantime the ntnu-username is removed from their profile (no idea why this would happen, but it just did), you can't approve them.

What's needed is just to check whether ntnu_username is empty, and give an appropriate error back to the dashboard.

**Comment by plusk** [comment]
This seems like a highly specific edge case that we've never encountered in my time. If it ever pops up, we'll look into it.
