### ISSUE TITLE
Several of the Profile tabs look like crap

### ISSUE THREAD

**Issue by myth** [dotkom/onlineweb4#1230]
This should be an easy task. The issue is really just that tabs like password change and privacy look like crap.

Also, the tabs use different page-widths, which looks really really silly.

Take inspiration from the "Prikker & Suspansjoner" or "E-postinnstillinger" (except for page-width) views, which look decent. All tabs should utilize the container div's width for flow-text.

Bullet points include stuff like:
- Use the same header sizes
- Try to use same grid layout for dual-pane stuff
- Tabs that have no paragraph text should get some. Privacy should atleast have some explanation of what activation or deactivation means. Where is it in effect etc. Password change could have some hints and ideas about good password routines.
- Use the same paragraph structure
- Remove those buttugly big blue privacy boxes with something more elegant
- In general, add some more space and air
- When clicking down the nav-pills (tabs), content anchors should not be bouncing around like it is now. Headers should start at same anchor etc.

**Comment by Aborysa** [comment]
Changed the styling of the buttons in "Personvern", hopefully they aren't that ugly anymore.

**Comment by sardred** [comment]
Closing as this will be handled in OWF
