### ISSUE TITLE
Featured events (ref Åre being pushed outside frontpage).

### ISSUE THREAD

**Issue by myth** [dotKom/onlineweb4#1272]
By mail request

Like the "featured" flag on articles

**Comment by melwil** [comment]
I had a counter proposal to this, which is to feature events in the order that registration becomes available. If it doesn't have a registration start, just use event start.

You can then display it on the front in one of two ways, I imagine:
* Sorted after registration_start until event_end has passed
* Sorted after registration_start until registration_end, then sort on event_start

This makes it unnecessary to implement this flag, and a simple property in events can make it easy for each event to tell a system what is wishes to be sorted by.

Only "issue" here is that you can't use a plain `.order_by` to sort them of this strategy is used, unless you can somehow get the ordering to take registration into account.

**Comment by sklirg** [comment]
> * Sorted after registration_start until event_end has passed

Would make events like Åre and Hovedekskursjon stay in the first position(s) until they pass, which is not the wanted result.

> * Sorted after registration_start until registration_end, then sort on event_start
Is a nice implementation.

> Only "issue" here is that you can't use a plain `.order_by` to sort them of this strategy is used, unless you can somehow get the ordering to take registration into account.

I'm sure you can, e.g. using a manager. (Which renders your statement correct: not using a simple order_by.)

**Comment by melwil** [comment]
Well, thoughts on the second one? It's the one I consider the most sane, and it basically solves the problem that the "featured" flag tries to solve, without any user intervention needed.

**Comment by sklirg** [comment]
I'll have a look at it and push a PR.

**Comment by nixolas1** [comment]
Sorting on registration_start until registration_end will make events like Åre stay in first place until December. 
Is that that specific event's fault, or should this may be taken into consideration and have a maximum duration the event can be sorted on registration_start?

**Comment by hernil** [comment]
@nixolas1 Se #1355
