### ISSUE TITLE
Mobile scrolling stuck at dashboard approvals

### ISSUE THREAD

**Issue by myth** [dotKom/onlineweb4#1283]
Scrolling is locked / broken. Cannot scroll downward.

![img_1752](https://cloud.githubusercontent.com/assets/2415878/10666114/f09133f2-78cf-11e5-86dc-cb6e9921140c.jpg)

Device is iOS, both Chrome and Safari give same results.
I know we are not putting epmhasis on mobile experience, but it must be possible to perform the actions on mobile devices, even though the layout is not optimal.

**Comment by hernil** [comment]
I have noe way of debugging this in a good way. @tmn do you have any starting point to approach this?

**Comment by tmn** [comment]
It's probably the usage of `overflow: auto;` and the `min-height: 100%;` on `.left-side` and `.right-side`. 

**Quick fix:**

* remove the `min-height: 100%;` and from both `.left-side` and `.right-side`
* remove `overflow: auto;` form `.right-side`
* add `bottom: 0;` to `.left-side` (to make it stretch all the way to the bottom)

And should the `.right-side` be an `<aside>`? Isn't it the main content of the dash?
