### ISSUE TITLE
Open source onlineweb4

### ISSUE THREAD

**Issue by hernil** [dotKom/onlineweb4#1286]
As discussed numerous times in the past, and now on Wednesday. We'd like to open up the onlineweb4 repo and license it under an open source license. This time we actually set a deadline for a decision to Wednesday 28th so feedback should be in before that. 

Things to do: 
- [x] decide upon a license
- [x] do proper changes in accordance to django-wiki GPL-license 
  - turns out we do not have to do anything
- [x] check for keys or passwords in files
  - Secret has been regenerated for good measure
  - Re-rolled Stripe keys
- [x] do a quick check of issues to look for things that should be removed pre-opensourcing
- [x] contributors file
- [x] open the repo
- [ ] spread the gospel of onlineweb4

**Comment by OptimusCrime** [comment]
Hello world

**Comment by michaeljohansen** [comment]
Suggestion on spreading the gospel: Push it out via the Foreninger mailing list. Perhaps even push it out via the FB-group for leaders at Gløshaugen as well.
