### ISSUE TITLE
Linking to signup on external events

### ISSUE THREAD

**Issue by lizter** [dotkom/onlineweb4#1306]
_Suggestion_

https://online.ntnu.no/events/205/studlan-6-8-november/
Events like these which actually requires external signup could maybe be linked to from our page.

"Dette arrangmentet har ekstern [påmelding](link here)".

This could be implemented as a new inline object that is mutually exclusive with the attendance event.

Could be smart to have like a "You are now leaving online.ntnu.no" thing if the link is pressed

**Comment by hernil** [comment]
That would be nice. It might happen that we have some sort of "attendance" other places as well. Like Facebook for X-fest or similar events.

**Comment by plusk** [comment]
We'll handle this in OWF.
