### ISSUE TITLE
Change stripe key data structure to dict

### ISSUE THREAD

**Issue by melwil** [dotKom/onlineweb4#1310]
Having more than one set of stripe keys means clutter if they are stored in a list. A much safer way is to use a dict for that kind of storage. Not only is it safer, but also a lot more understandable in code.

```python
key = STRIPE_KEYS[0] vs STRIPE_KEYS['arrkom']
```

**Comment by hernil** [comment]
Yep, unless @Torrib can remember why he didn't do it this way we should change it.

**Comment by hernil** [comment]
Bump @Torrib

**Comment by sklirg** [comment]
If we are refactoring how this is done, let's do it this way: 
> It [keys] should be stored in the same location as other credentials we use, and customized as environment variables in the launch scripts for the application [rather than in onlineweb4.settings].
https://github.com/dotKom/onlineweb4/issues/1209#issuecomment-157680679 & #976.
