### ISSUE TITLE
Figure out what to present in Dashboard start page

### ISSUE THREAD

**Issue by myth** [dotkom/onlineweb4#1318]
When our committee representational model is in place, it would be nice to customize the dashboard landing page and display relevant items and notifications.

Other ideas are ofcourse welcome.

For dotKoms part, statistics and monitoring stuff could be nice.

**Comment by sklirg** [comment]
We could possibly ask committees about what they want to see.

For the committees with only one relevant module in the dashboard, they could be redirected to that one.

Suggestions:

BedKom & FagKom: 
- Status/summary of upcoming attendance events (number of attendees, ...)

TriKom:
- Status of inventory, any items nearing expiry / nearing empty?

**Comment by plusk** [comment]
We're quite happy with the current start page. We'll make a new dashboard for OWF in the future, and might revisit some of these ideas then.
