### ISSUE TITLE
Webshop nitpicking

### ISSUE THREAD

**Issue by Torrib** [dotkom/onlineweb4#1338]
- [ ] Overview over users orders.
- [ ] Save button in product add view should be under as well so the user does not have to scroll back upp to save.
- [x] Breadcrumbs does not work.
- [ ] Refund logic
- [x] Dashboard overview over payed products that Prokom needs to order.
- [ ] Send notifications if users have unpaid orderlines where products have a deadline.
- [x] If a size has stock display it.
- [x] If a selected size has a stock and is empty disable the "add" button
- [ ] Dashboard support for sizes
- [x] Reduce stock on purchase (Both total and ProductSize)
- [ ] Fix product list on mobile.
- [x] Add list of products in the confirmation email.
- [ ] Fix gallery functionality so images works properly for the webshop.
- [ ] Properly implement deadline handling.
- [x] Product description is duplicated on regular desktop view (e.g it is rendered twice).
- [ ] Mobile view content is generally not good. Most of the content overlaps and floats do not break correctly.
- [x] Top bar menu item Webshop overflows and is interpolated with dropdown user menu on medium width
- [x] There is an issue with reverse matching in dashboard (probably related to slug generation, ref stacktrace)
- [x] Breadcrumbs look terrible, use bootstraps pre-built breadcrumbs for navigation, and the h3 for titles as is tradition.
- [x] The `,-` means there is no remainder and it is a flat price. Either `150,-` or `150,00kr`.
- [ ] Add functionality to reduce amount in cart without deleting entire order line.
- [ ] `apps.payment.views:145 Name bought OrderLine object for 120.00 kr` is not a very good log entry. Needs moar ID's, hash, textual description, CSV of product ID's or something.

**Comment by myth** [comment]
- [ ] Product description is duplicated on regular desktop view (e.g it is rendered twice).
- [ ] Mobile view content is generally not good. Most of the content overlaps and floats do not break correctly.
- [ ] Top bar menu item Webshop overflows and is interpolated with dropdown user menu on medium width
- [ ] There is an issue with reverse matching in dashboard (probably related to slug generation, ref stacktrace)
- [ ] Breadcrumbs look terrible, use bootstraps pre-built breadcrumbs for navigation, and the h3 for titles as is tradition.
- [ ] The `,-` means there is no remainder and it is a flat price. Either `150,-` or `150,00kr`.
- [ ] Add functionality to reduce amount in cart without deleting entire order line.

**Comment by plusk** [comment]
We'll be rewriting the webshop completely in OWF. AS a result, we'll let it be ugly until then, just like the three years since this issue was opened.
