### ISSUE TITLE
Refactor project structure, templates and staticfiles in their respective apps

### ISSUE THREAD

**Issue by sklirg** [dotKom/onlineweb4#1339]
## Intro

With the project getting bigger and bigger, having the directories for `templates/` and `files/static/` separate from the app itself can get complex and confusing.
## Package by feature

The _package by feature_ concept was mentioned on Slack today, which has the mantra that by removing one package you have removed everything with regards to that package: you will not be left with any orphans to that app. (Except for apps using that app, obviously, but that's another matter) 

_While the mantra is nice, it's not the reason for this proposed issue. The onlineweb project is a niche project and has a lot of dependencies from everywhere in the project. Simply removing one app would remove a lot of features and probably bring with it a huge refactoring process._
### Proposed change

Move 
- templates
- static files (img, javascript, css, less)

for all apps to the apps' own directory.

---
#### Project structure before change

```
apps/
  articles/
    dashboard/
    models.py
    views.py
  events/
    dashboard/
    models.py
    views.py
files/
  static/
    img/
    js/
templates/
  articles/
    index.html
  events/
    index.html
```
#### Project structure after change

```
apps/
  articles/
    dashboard/
    templates/
    static/
    models.py
    views.py
  events/
    dashboard/
    templates/
    static/
    models.py
    views.py
```

It could also become easier to load relevant static files for each app if that's of any concern.

---

With #1260 still being open, and me having thought about moving the api-relevant stuff into an api folder in each app, I think this could be a nice refactor and cleanup of the project.
While it's not much work, (really, it isn't) it requires a bit of testing to make sure everything works as it should.

**Comment by sklirg** [comment]
If there are any arguments (for or against), suggestions or other thoughts or comments, fire away.

**Comment by cXhristian** [comment]
Yes, please!

**Comment by sklirg** [comment]
I think we can discard this with our move to a react-based frontend, which has a nice structure already.
