### ISSUE TITLE
Login at ci.frigg.io

### ISSUE THREAD

**Issue by frecar** [dotKom/onlineweb4#1340]
Hi,

In order to have access to post status messages to this github project, we need someone with access to the repository to login at http://ci.frigg.io. Click "Login" and sign in with Github.

**Comment by frecar** [comment]
@hernil  :)

**Comment by hernil** [comment]
Done. However it would be nice to limit access that the application requests. Now I had no choice but to allow Frigg access to all my organizations :)

**Comment by frecar** [comment]
Great! Yes, we are looking into that :)
