### ISSUE TITLE
Add Seniorkomiteen to list of positions.

### ISSUE THREAD

**Issue by sverrejb** [dotkom/onlineweb4#1346]
On the add positions page on my profile it is not currently possible to add "Seniorkomiteen" as a position.

**Comment by hernil** [comment]
We'll do this when getting to #1209 :-)

**Comment by sverrejb** [comment]
Goodie! :)

**Comment by sklirg** [comment]
Let's just add this now since we haven't really started on #1209 yet.

**Comment by oleast** [comment]
Fixed in #2097
