### ISSUE TITLE
Rutinator

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#1347]
Rutinator is the new app designed to make people do their tasks in a timely manner.

It's being developed by @junglebooboo and @Mangokitten.

_For starters it's going to be a dashboard app. Might get some custom views for mobile friendlyness etc._

This issue is mainly used as a reference and todo list for the app.

---
### Some kind of spec

Models:

```
Task
- group -> if group is chosen: - person
- title
- description
- completed
- completed date
- deadline
```

Functions

```
- Select random person from group to do this task
- Send notification emails
- Notifications for dashboard
- Integration on dashboard front page
- Recurring tasks
```

---
## Progress

Models
- [x] Custom task
- [x] New
- [x] Edit
- [x] Clean overview

Functions
- Selection
  - [x] Select person for task
  - [x] Select group for task
  - [x] Select random from a group
  - [ ] Option for multiple groups
- Users
  - [ ] Filter users by group
  - [ ] User picker from group
  - [ ] Rotation - check users already picked (to avoid repetitive selection)
- Notifications
  - [x] Send notification emails
  - [ ] Dashboard notifications
- Recurring tasks
  - [ ] One-time-tasks or recurring tasks
  - [ ] Interval (how often) if recurring
  - [ ] Send mail intervals (option)
Implementation
 - [ ] Step-by-step view (tabs/windows)
 - [ ] Make it an "app"

**Comment by sardred** [comment]
This is like super-dead now, right? Can we close the issue @oleast?

**Comment by oleast** [comment]
I agree that we should close it.
