### ISSUE TITLE
Only display stock linked to you own committee 

### ISSUE THREAD

**Issue by chrlofs** [dotkom/onlineweb4#1348]
When you click at inventory in dashboard, you will get all the stuff from coffee, noodles too soda. FagKom has no business with how much coffee or noodles we have in stock and I wish to only see the stuff my committee has in stock. 
![skjermbilde 2015-11-12 kl 21 40 24](https://cloud.githubusercontent.com/assets/9264978/11130574/068ac328-8986-11e5-922d-e54b4523be90.png)

**Comment by myth** [comment]
Needs to be regarded in unison with the changes that #1538 will introduce.
