### ISSUE TITLE
Label on events and event sorting

### ISSUE THREAD

**Issue by chrlofs** [dotKom/onlineweb4#1358]
Display labels on events at the frontpage and the archive like "Kurs", "Bedriftpresentasjon", "Kontorarrangement", "Arrangement", "Andre", "Ekskursjon" etc...

We in fagKom want to change how we make events on ow next semester, instead of "Kurs med XXX" we want to write "Programming Ladder med XXX" and to make it easier for our members we want to have labels with the event type . 

We also want an option to sort the events based on the label.

**Comment by sklirg** [comment]
It is now possible to filter events based on event type. Is it still in your interest to show a label for an event, with what type of event it is, or is the filtering enough?
