### ISSUE TITLE
Use watson when searching for users

### ISSUE THREAD

**Issue by hernil** [dotKom/onlineweb4#1360]
This is for the dashboard.

**Comment by sklirg** [comment]
We do search using Watson in dashboard.

[User search view](https://github.com/dotKom/onlineweb4/blob/develop/apps/authentication/dashboard/views.py#L156) imports [SearchView](https://github.com/dotKom/onlineweb4/blob/develop/apps/authentication/dashboard/views.py#L17) from [watson.views.SearchView](https://github.com/etianen/django-watson/blob/master/src/watson/views.py#L85)
