### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by sklirg** [dotKom/onlineweb4#1367]
# Continuous Integration

Provide automated features for building and deploying code.

We currently have a development / staging server live at dev.online.ntnu.no. I'd like to see this being automatically bumped to develop HEAD on any commit. 

In addition, to save developers some time; sync all data from production to develop either regularly, or during the aforementioned deployment. This ensures we have a testing area which very closely resembles live.

Quote:

> Imagine developers being able to spin up their own copies of a DB in a self-service manner, via a few lines of Puppet or Chef code committed into a source control repo.

[source](https://dantehranian.wordpress.com/2015/01/13/solve-the-devops-gap-deploy-fresh-app-data-in-test-environments/) :heart_eyes: 

Okay this might be far fetched for now. 

Any input? What more can we automate for development purposes?
## ToDo
- [x] Automatically deploy develop branch to dev.online.ntnu.no
- [ ] Sync production server data to develop server

**Comment by myth** [comment]
I would love to see a full pipeline setup that ends in deployment both for the HEAD of develop as well as triggered on each release. Like the ones in Concourse or the new Jenkins 2 pipelines.

**Comment by sklirg** [comment]
This is not really an issue regarding OW4, but rather the operation of it. Let's move it to somewhere more appropriate.
