### ISSUE TITLE
Adding links to user profile's external url's

### ISSUE THREAD

**Issue by niklasmh** [dotKom/onlineweb4#1370]
Would be nice if the url's to github and linkedin were links on the user profiles.

Another suggestion: if the "https://" protocol is missing on github links the form could assume the user has filled in the username. Links on linkedin, on the other hand, are a bit more complicated if you don't have a pre-generated link, so there could be an infobox with info about how to get this short and clean url from linkedin - if this feature gets implemented.

**Comment by sardred** [comment]
@niklasmh is this fixed? Seems like you've committed something, but that's about it.

**Comment by niklasmh** [comment]
Since the user site is about to change later, I think it is best to wait until then. My solution did not seem to be the best practice. Hopefully the change will eighter solve this issue, or avoid it.
