### ISSUE TITLE
Request access to our Slack team

### ISSUE THREAD

**Issue by sklirg** [dotKom/onlineweb4#1371]
We could add a button on the profile page which sends an invite to the (primary) email address of the user.

We could even add a box during membership registration asking if they want an invitation to Slack, automatically sending an invitation email. Or include the token required for signing up in a Onlineweb-welcome-email. (Informing about various newsletters and such?)

With #1209, we could probably even automate group invites.

However, currently the Slack API does not support automatic invites. I came across [outsideris/slack-invite-automation](https://github.com/outsideris/slack-invite-automation), which POSTs to `/api/users.admin.invite`.

**Comment by sklirg** [comment]
If we want to open up Slack for anyone (not only Online members) (like the IRC channel we run on freenode), we can look into https://github.com/rauchg/slackin.

**Comment by duvholt** [comment]
Fixed by #1629
