### ISSUE TITLE
Replace django-chunks

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#1376]
We should replace [django-chunks](https://github.com/clintecker/django-chunks). It's not actively maintained and it fails on Django 1.9 because it uses deprecated functions.

Our uses:
1. Frontpage, infotext regarding each committee.
2. Information texts for Offline

The functionality of 1 is scheduled to be removed in #1209 (frontpage, about all committees).
The functionality of 2 needs to be completely replaced.

As of now this module is hindering a Django version upgrade so we might want to do some temporary fix for this, and implement the change coming in #1209 at a later time. This way, we can upgrade to Django 1.9 asap.

Suggestion for temporary fixes:
- Install https://github.com/funkybob/django-flatblocks and port the data over to that module (or another similar module)
- Move current chunks into the html-templates, effectively hard-coding them into there for the time being (this removes edit-functionality from the administration panel for the time being)
- Flatpage for "about us"

**Comment by myth** [comment]
I believe Django already has built-ins that can be used. The flatpages app is an optional that basically does the same thing.

**Comment by sklirg** [comment]
The problem with flatpages is that it renders a whole page, which would not work for our frontpage  (which has events, articles etc.). 
We could, however, move that content to a separate page (about us) and show it there. That page could then be updated upon merging of a fix for #1209.

**Comment by myth** [comment]
Reuse just the models then, or roll our own. It's not like it's much complexity in chunks.

**Comment by myth** [comment]
Bump, since the complexity is very low, and this is an excellent entry-level project for the new guys to get to know python package development in general and django addons in particular. Since chunks is no longer maintained, we should task ourselves with creating a similar package, and also add some additional features wee see fit.

**Comment by sklirg** [comment]
I forked it and fixed the bugs for the 1.9 PR. Fwiw.

**Comment by sklirg** [comment]
Should we write some specs for this module, so any takers know what's required?

**Comment by sklirg** [comment]
Since this mainly was a blocker for bumping to Django 1.9, I'll close this for now. If we want to, we can modify the "chunks" to basically be the whole about us page, and provide API endpoints for them instead of template tags.
