### ISSUE TITLE
Event opening in the future has button to box with membership info

### ISSUE THREAD

**Issue by OptimusCrime** [dotKom/onlineweb4#1378]
> Påmeldingen er ikke åpnet enda. 
> Mer

Clicking Mer opens dialog with membership information, which makes no sense in this contex.

**Comment by OptimusCrime** [comment]
We could also enhance the template to use the `status_code` instead of looking for variables everywhere. This requires fix for #1379.

https://github.com/dotKom/onlineweb4/blob/develop/templates/events/details.html#L176
https://github.com/dotKom/onlineweb4/blob/develop/templates/events/details.html#L192

**Comment by sklirg** [comment]
Events with closed attendance also does this: https://online.ntnu.no/events/84/hovedekskursjon-2015/
