### ISSUE TITLE
Minimize spacing between infobox and description in event details

### ISSUE THREAD

**Issue by OptimusCrime** [dotKom/onlineweb4#1381]
Email:

> Kan dere gjøre mellomrommet mellom den øverste boksen og teksten på eventer på onlineweben litt mindre? Hadde sett litt finere ut :)

This is a design problem because the info box and the description of the event is in separate rows. The info box is in the same row as the action box, to have the correct ordering on narrower devices. This becomes an issue when the action box column is much taller than the infobox.

I have no good ways to solve this problem.

Illustration of this issue can be seen here: https://online.ntnu.no/events/199/are-2016/

**Comment by niklasmh** [comment]
Seems like flexbox is one solution, as the flexbox technology can fix the order and make two columns instead of two rows. But do we handle flexbox on the website at all? It should work world wide by now.

Meanwhile I will experiment with some float.
