### ISSUE TITLE
SplashYear matching query does not exist

### ISSUE THREAD

**Issue by sklirg** [dotKom/onlineweb4#1382]
https://github.com/dotKom/onlineweb4/blob/develop/apps/splash/models.py#L11 tries to get a SplashYear, but there are no objects matching the query, so it triggers an exception. 

> DoesNotExist: SplashYear matching query does not exist.

How to quick-fix: Create a SplashYear which satisfies the matching query.

**Comment by cXhristian** [comment]
IMO this should be properly fixed so we don't get the same errors next year.
Should be a pretty easy fix.
