### ISSUE TITLE
Extend dashboard DTP with time of day

### ISSUE THREAD

**Issue by myth** [dotKom/onlineweb4#1386]
Currently only the date portion of the datetimepicker is active.

Reconfigure `dashboard.js` to include the time of day as well.

**Comment by sklirg** [comment]
:+1:

**Comment by niklasmh** [comment]
Fixed one class with datetime, one with date only and one with just time. Elements affected by the .dpt-class will change to datetime unless only date is specified with the .dp-class, or only time is specified with the .tp-class (every element is now .dtp which is a full datetime).
