### ISSUE TITLE
Reduce size of carousel arrows in the `Offline` section

### ISSUE THREAD

**Issue by tmn** [dotKom/onlineweb4#1389]
Bad ratio between button (the grey background) and the white arrow in the `Offline` section on the front page

**Comment by sardred** [comment]
Would it be a viable option to redesign these chevrons? Seeing as no other symbols on the page follow this theme (white/transparent symbol with gray circular background with a semi-transparent white circle around), wouldn't we be wiser to turn them into orange chevrons instead? We use that design for the section right underneath(Bedrifter) and it makes them pop more.

@hernil thoughts?

**Comment by hernil** [comment]
I think the orange ones look quite good :smile: 

Btw. regarding "poping" http://theoatmeal.com/comics/design_hell ^^
