### ISSUE TITLE
Extras not displayed

### ISSUE THREAD

**Issue by chrlofs** [dotKom/onlineweb4#1397]
When I look at the list of attendees for events at the dashboard, the summary of extras at the bottom is just empty. This is quite crucial when ordering food too 40 people, the error occurred last night I think. 

There is also a problem when the extras are actually displayed, the None-choice is not counted right.

Pic of the problem:
![skjermbilde 2016-01-28 kl 09 17 34](https://cloud.githubusercontent.com/assets/9264978/12638765/05be5008-c5a0-11e5-9c71-fc0c22183051.png)

**Comment by sklirg** [comment]
Probably due to events branch rebase. Should only be a matter of looking
through the diff and find what was lost and where.

**Comment by sklirg** [comment]
What do you mean by "when the extras are actually displayed"?

**Comment by chrlofs** [comment]
Before this bug when the extras was displayed (yesterday), I had one attendee who had not chosen any extra. At the total the option "None" displayed 0.

**Comment by nixolas1** [comment]
Fixed last week by @cXhristian
