### ISSUE TITLE
Add option to edit additional fields on active posters

### ISSUE THREAD

**Issue by myth** [dotKom/onlineweb4#1412]
Ref mail, add option to edit the amount of "bonger" on active poster orders.

**Comment by sklirg** [comment]
Fixed by https://github.com/dotKom/onlineweb4/pull/1429.
(ps @nixolas1 , syntax is 
"fix #issue" or any other keyword mentioned in [2]

Sources: 

- https://github.com/blog/1506-closing-issues-via-pull-requests
- [2] https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by OptimusCrime** [comment]
@sklirg Does not "fix #issue" automatically close the issue that is referenced? We would like to avoid that.

**Comment by sklirg** [comment]
It does. Why would we avoid closing an issue that a PR solves?

**Comment by OptimusCrime** [comment]
I though we decided not to do that automatically to avoid closing issues that were not 100% resolved.

I might be wrong though.

**Comment by sklirg** [comment]
What if it is 100% resolved?

**Comment by OptimusCrime** [comment]
Then the end of days are upon us.

**Comment by myth** [comment]
I suspect you might have dreamt this

**Comment by sklirg** [comment]
99% of our issues are closed this way.
At least these 300 PRs do it that way.
https://github.com/dotKom/onlineweb4/issues?utf8=%E2%9C%93&q=fixes++is%3Aclosed

**Comment by OptimusCrime** [comment]
END OF DAYYYS
