### ISSUE TITLE
An unknown bug is causing ResponsiveImage.wide not to be stored on disk

### ISSUE THREAD

**Issue by myth** [dotKom/onlineweb4#1413]
All ResponsiveImage image versions except wide (non 16:9) are stored correctly, This causes rendering of ResponsiveImage objects in dashboard etc to drop a 500, as well as possibly not allowing related objects using ResponsiveImage to be shown in API etc.

**Comment by myth** [comment]
This seems related to the issue regarding articles not being displayed on the front page, even though there are no obvious errors. Manually cropping and uploading the `image.wide` related file solved that issue.

**Comment by melwil** [comment]
What was the manual fix for this? It's still blocking articles for the front page.

**Comment by myth** [comment]
Download the LG version (its the same filename as the thumbnail, which is searchable but not initially listed in the dashboard gallery overview), manually crop it to the wide article format. Upload it to the `images/responsive/wide/` folder with the same filename.

**Comment by myth** [comment]
Fixed in #1451
