### ISSUE TITLE
Build status svg is unknown

### ISSUE THREAD

**Issue by hernil** [dotKom/onlineweb4#1415]
Even though develop builds just fine on frigg the build status svg in readme returns unknown. @frecar mind having a look? :smile:

**Comment by sklirg** [comment]
I'm guessing it's checking the master branch (which we do not have).

> To get a nice build badge in your readme to show everyone that you build is a success, or warn people that it is broken and the *master branch* might not work at the moment, just add the code below.

Source: https://frigg.io/docs/badges/

However, their views support keyword arguments [\[0\]](https://github.com/frigg/frigg-hq/blob/6288f94cc48c3d38dc473aa913732477d9cb46f9/frigg/projects/views.py#L11), but for some reason it doesn't return the correct badge for e.g. https://ci.frigg.io/dotKom/onlineweb4.svg?branch=develop or https://ci.frigg.io/dotKom/onlineweb4.svg?branch=django19. Also, a non-existant branch returns last build status of master. https://ci.frigg.io/frigg/frigg-hq.svg?branch=xxadsfds

[0]: https://github.com/frigg/frigg-hq/blob/6288f94cc48c3d38dc473aa913732477d9cb46f9/frigg/projects/views.py#L11

Probably relevant to raise this issue in their repository.

**Comment by cXhristian** [comment]
Updated with some undocumented urls I found. 

![Coverage](https://ci.frigg.io/badges/coverage/dotKom/onlineweb4/develop/)

![Build](https://ci.frigg.io/badges/dotKom/onlineweb4/develop/)

I think the problem is that they are missing branch support for the .svg urls. Might make a pr later.

**Comment by OptimusCrime** [comment]
The badges you just linked to supports branches?

**Comment by OptimusCrime** [comment]
![Build](https://ci.frigg.io/badges/dotKom/onlineweb4/email_templates/)

**Comment by OptimusCrime** [comment]
Ah, for the .svg files. Gotcha.
