### ISSUE TITLE
Focus stays on chevrons on Offline section

### ISSUE THREAD

**Issue by sardred** [dotKom/onlineweb4#1424]
If you click on the carousel chevrons in the "Offline" section of the frontpage, the the focus changes their color to a darker gray/black. After the transition is complete, the focus/color stays. Is this intended/wildly unimportant, or a mere oversight?

**Comment by hernil** [comment]
It's probably just a bug that has appeared with upgrading a lib, or making a minor change at some point. It's not intended, nor critical. But if you're having a look at this while working on #1389 you might as well see if you find the problem.

**Comment by sardred** [comment]
Isn't this standard behavior for focus, not a bug? Typically when you focus on a link, it takes you to some other page, so you don't notice it. In this case, our button doesn't take us away, so the change of color is still apparent after the button has done its work. One could demonstrate this by for example focusing on a text field (like making a comment here), and noting how it stays in focus until you focus on something else. I'll probably fix it momentarily regardless.

**Comment by OptimusCrime** [comment]
Adding focus to this is wrong imo. Hover is more than enough.

Adding:
```&:focus {
    .opacity(.5);
  }
```

To: https://github.com/dotKom/onlineweb4/blob/3aa45b96a012573dd375b099d62532bac0bca83b/files/static/less/offlinewidget.less#L15

Should solve the problem. It overrides the opacity of `0.9` added to `:focus` added by Boostrap.
