### ISSUE TITLE
Python 3 bugs

### ISSUE THREAD

**Issue by cXhristian** [dotKom/onlineweb4#1437]
- [x] Redwine top list
- [x] Genfors unicode errors
- [x] admin-panel shows `<a href="/">Onlineweb</a>` instead of clickable text

Please update the issue with any other python 3 bugs.

**Comment by OptimusCrime** [comment]
@MrHanSan is this fixed now?

**Comment by MrHanSan** [comment]
This is fixed

**Comment by OptimusCrime** [comment]
Then closed :)
