### ISSUE TITLE
Logo and links disappearing when site is resized

### ISSUE THREAD

**Issue by MrWe** [dotKom/onlineweb4#1453]
The logo and links in the header will disappear when window width is reduced, menu is opened and closed, and width is put back to fullscreen. 

Steps to reproduce: 
Reduce window width to less than 770px
Open hamburger menu
Close hamburger menu
Resize window to more than 770px

**Comment by niklasmh** [comment]
Should be easy to fix. Somehow the menu acually sets an inline style to display: none at the menu:

Window less than 770px:
![image](https://cloud.githubusercontent.com/assets/8504538/13599925/0c99dce4-e526-11e5-8f0a-8b45c42bf430.png)

Menu clicked:
![image](https://cloud.githubusercontent.com/assets/8504538/13599945/27aed610-e526-11e5-89b5-5e7ebbcbc532.png)

Menu clicked again:
![image](https://cloud.githubusercontent.com/assets/8504538/13600013/8d4bd8ce-e526-11e5-894e-0c71cdf08b38.png)


This overwrites the default css. So just removing the last step should solve everything.
