### ISSUE TITLE
Company.short_description field has lower max_length than database data

### ISSUE THREAD

**Issue by sklirg** [dotKom/onlineweb4#1459]
Some companies on https://online.ntnu.no has `short_description`s with a length longer than 200 characters. This makes it impossible to save the model without reducing the character count in that field. 

The field is a TextField which supports an arbitrary long length, so the `max_length` parameter set on the field is simply for form validation. 

I suggest bumping it to a reasonable amount.

**Comment by OptimusCrime** [comment]
Do we really need a max length for this?

**Comment by sklirg** [comment]
Not necessarily, it depends on how much text we want to display. 

I think it's fair to set a limit for an ingress, or "short description". However, 200 characters is too low a limit.
