### ISSUE TITLE
Menu bar change

### ISSUE THREAD

**Issue by niklasmh** [dotKom/onlineweb4#1461]
I am sure many already know about this; the menu bar has too large tabs (Could be because of "Webshop"). But why do not we change some of the words used instead? Especially "Karrieremuligheter":

![image](https://cloud.githubusercontent.com/assets/8504538/13605890/000421aa-e54a-11e5-8646-ed4746a6c3e3.png)

This could be:

![image](https://cloud.githubusercontent.com/assets/8504538/13605856/e3bf056e-e549-11e5-8e29-f20d27696ae3.png)

It is even easier to read. Is "Karrieremuligheter" more describing than "Karriere"? Is it nessesary?

**Comment by OptimusCrime** [comment]
+1
