### ISSUE TITLE
[Feedback] - Mail text is borked

### ISSUE THREAD

**Issue by Torrib** [dotKom/onlineweb4#1476]
The feedback notification mail is broken.
Probably after the python upgrade.

**Comment by sklirg** [comment]
Should probably check all other mails too.

**Comment by sklirg** [comment]
Though I think maybe @myth is looking into email templates? If not, this is
a golden time to do it. :)

**Comment by myth** [comment]
No I am not looking into E-mail templates. Too much had to be re-done to continue on that branch. Better to start from scratch. I'm currently focusing on #1474

**Comment by hernil** [comment]
Actually, you have WIP PR #1331 on the subject yourself, @sklirg :smile:

**Comment by sklirg** [comment]
😊
