### ISSUE TITLE
Deleted email address can't be added back

### ISSUE THREAD

**Issue by nornes** [dotKom/onlineweb4#1480]
Deleting an email address from the user profile makes it impossible to add that same address back. Attempting to add it back gives a message saying a user with the NTNU-username is already registered. 

Problem persists weeks after the address was removed.

**Comment by sklirg** [comment]
For steps to resolve this issue, have a look at how the front-end view
handles removal of email addresses.

That workflow should be moved to signal handlers, so it will happen during
deletion in any way, not just the button click in front-end.
