### ISSUE TITLE
Events open for "Other masters" can be misleading

### ISSUE THREAD

**Issue by sklirg** [dotKom/onlineweb4#1506]
Any events open for "Other masters" ("Annen mastergrad") are actually only open for members of Online, not anyone. We've just received a request to specify this a bit more clearly on the event detail page.

**Comment by sklirg** [comment]
I suggest something along the lines of https://github.com/dotKom/onlineweb4/pull/1342.

**Comment by hernil** [comment]
I don't think there's any need to over-engineer this too much. Something along the lines of "Annen informatikkmaster" or "Annen mastergrad (Online)" would probably do just fine.

**Comment by sklirg** [comment]
I think it's fine. We haven't received any further inquires regarding this anyways.
