### ISSUE TITLE
Zip codes must be 4 digits

### ISSUE THREAD

**Issue by sklirg** [dotKom/onlineweb4#1509]
![screenshot 2016-04-11 17 29 08](https://cloud.githubusercontent.com/assets/5422571/14432568/03b9526c-000b-11e6-8ec7-91d2cef772d2.png)

Happens during user sign up.

**Comment by melwil** [comment]
https://github.com/dotKom/onlineweb4/blob/develop/apps/authentication/forms.py#L123

```if re.match(r'\d{4}', zip_code):```

if not please :D Now it actually invalidates only the correct ones.

**Comment by OptimusCrime** [comment]
Hahaha

**Comment by sklirg** [comment]
Fixed in c9b9c0efd488918c47a74c10fd48d7e151dfd54e.
