### ISSUE TITLE
Doppins for dependency management

### ISSUE THREAD

**Issue by sklirg** [dotKom/onlineweb4#1529]
Should we drop in [doppins](https://doppins.com/) to handle requirements.txt-dependencies? That way we get a PR every time there's a dependency upgrade, rather than we having to check each and every package now and again to check for new releases.

**Comment by cXhristian** [comment]
I would like this. It might get a bit spammy, but with proper mail filters I don't see a big problem with it.

**Comment by myth** [comment]
:+1: from me as well
