### ISSUE TITLE
Create new tab for "interessegrupper" and clean up the "nodekomiteer" tab

### ISSUE THREAD

**Issue by Senjinx** [dotKom/onlineweb4#1534]
Clean up the "nodekomiteer" tab on the frontpage. Some of these entries are no longer a "nodekomité"

**Comment by chrlofs** [comment]
In my opinion, the front page should have one chunk for each "nodekomité" and rename the existing chunk named "nodekomiteer" to "interessegrupper".

**Comment by OptimusCrime** [comment]
I though they were called "nodekomiteer" by Online? I though this was stupid too, but "nodekomiteer" was the name chosen at genfors in 2015.

**Comment by Senjinx** [comment]
It was changed at genfors 2016, with the addition of "interessegrupper". Some of these are no longer categorized as "nodekomiteer" anymore, hence my issue.

**Comment by OptimusCrime** [comment]
Oh. I was not aware of this.

**Comment by Senjinx** [comment]
The issue was fixed <3
