### ISSUE TITLE
Refactor inventory to handle check-ins and check-outs of items

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#1538]
Upon request, the committees handling inventory stock want to be able to check in and out items from the inventory.

To solve this, we'll drop the expiration-date functionality, and implement a checkin / checkout system. It has also been voiced interest in being able to have some kind of handheld device with easy access to this checkin/checkout system, so responsiveness and ease of use on smaller devices should be a priority.

**Comment by sklirg** [comment]
Feature: Log of check-ins and check-outs (a text box would suffice, but it's often in relation to an event - though not always (e.g. trikom selling sodas in the office)).

**Comment by plusk** [comment]
It seems like something like this exists by now, or isn't really needed. Maybe we just didn't understand the issue. Either way, we're closing until trikom requests something similar, or somebody can explain to us what we're missing.
