### ISSUE TITLE
Preview changes position on resize when editing wiki articles

### ISSUE THREAD

**Issue by MrWe** [dotKom/onlineweb4#1543]
When resizing the preview using mouse in bottom right corner, the popover changes position. 

How to replicate:
1. Go to edit on an article.
2. Press "preview"
3. Resize popover with mouse on bottom right corner.

**Comment by sklirg** [comment]
I guess this is a django-wiki issue. Their [demo](http://demo.django-wiki.org/) is currently offline, so I can't check.

**Comment by sklirg** [comment]
Verified - it happens in the official Django-Wiki repository. Go [here](https://demo.django.wiki/Test/) and reproduce it. Please report this bug to Django-wiki instead.
