### ISSUE TITLE
Use is_staff rather than membership of group to define staff status

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#1566]
I think it'd be cleaner to check if a user is a staff user account (staff is not the same as administrator / superuser) rather than check for the membership of the group "Komiteer".

Since all committee members are synced to this group, we could make sure any persons synced to the "Komiteer" group has the is_staff flag.

**Comment by myth** [comment]
Sure, should have been done in that sort of way in the first place. But that's on me :)

**Comment by oleast** [comment]
`is_staff` should be set based on if a user is in a group of type `COMMITTEE` or `NODE_COMMITTEE`
