### ISSUE TITLE
Redesign events "extras" in frontend

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#1567]
We've added both "extras" and "payment" as options inside the attendance-box on the events detail page. This can quickly become messy, especially if adding multiple payment options (1). 

Also, the "extras"-dropdown looks like it was made in a hurry. I think we can make it look nicer. 

We could even combine the two, so that after you've chosen your "extra" (in lack of a better name), you get prompted with the "pay now" button (will only happen if more than one payment alternative) (NOT UI :octocat: )

**!!!** "extras" as defined in the title does **not** refer to an attendance event's "extras" option **!!!**

(1)
![pasted image at 2016_05_03 15_44](https://cloud.githubusercontent.com/assets/5422571/14985329/5c775082-1147-11e6-8e2d-618f2cbb9052.png)

**Comment by sklirg** [comment]
We could probably re-engineer this whole system and add support for some other relevant stuff.

Things we connect to events at the moment are
- attendanceevents
- feedback schemas
- payment stuff
- "extra" for an event, like food choice or some other preference

We could make these even more pluggable, and add it in its own section of the site. If they are " complicated" (more than just "pay this" or "select this"), we could spawn a modal. It could be as simple as a list of links that opens a modal or shows its status (completed / incomplete).

Maybe something like:

[event details are here]
[event image]
[event tasks]
- [ ] feedback schema
- [x] payment
- [x] event extra: pizza

**Comment by plusk** [comment]
We'll handle this in OWF.
