### ISSUE TITLE
Consider adding Sentry + Raven

### ISSUE THREAD

**Issue by myth** [dotkom/onlineweb4#1585]
Should we fire up [Sentry](https://getsentry.com) with [Raven](https://pypi.python.org/pypi/raven) (python client for Sentry) for teh lulz?

It looks kinda nice.

**Comment by sardred** [comment]
Looks neat. What about pricing though? If I'm not mistaken, there's no free option for us as a non-profit here. Don't get me wrong, I do love me some lulz, but is it worth spending any amount of time on setting it up if we can't keep it?

**Comment by sklirg** [comment]
> When your trial expires we'll downgrade you to our free tier. Our free tier is limited to a single user and 250 events per day.

**Comment by sardred** [comment]
> I suppose after the free trial, you do get downgraded to a free plan of sorts, but it seems fairly limited.

**Comment by myth** [comment]
Closing since it is not interesting if it costs :dollar:

**Comment by sklirg** [comment]
Got it for free for nonprofits, reopening.
