### ISSUE TITLE
Make splash a bit more mobile-friendly

### ISSUE THREAD

**Issue by sklirg** [dotKom/onlineweb4#1594]
So much blank space for a mobile user, as well as tiny text.

![2016-07-06 15 19 21](https://cloud.githubusercontent.com/assets/5422571/16623364/edce22b2-439d-11e6-8ce7-10cde30ec835.png)
![2016-07-06 15 18 51](https://cloud.githubusercontent.com/assets/5422571/16623365/edd6bb5c-439d-11e6-998c-e10ec066b291.png)

Maybe have a look at https://github.com/dotKom/Online-splash/pull/29 ?

**Comment by sardred** [comment]
I took a quick look at the PR and I'm not sure if it fully covers it. It doesn't seem to actually add the mobile stylesheet that was made, and when added it completely messes up the desktop version. Moreover, the mobile interface ends up looking hella wonky. It's far from perfect, but it might be better than what's there currently.

**Comment by sardred** [comment]
Closing this as we're making a new splash page in a different repo (https://github.com/dotKom/glowing-fortnight)
