### ISSUE TITLE
Inventory dashboard tablesorter is bound twice.

### ISSUE THREAD

**Issue by myth** [dotKom/onlineweb4#1597]
Results in sorting on a table header ending up in descending order each time.
Cause is https://github.com/dotKom/onlineweb4/blob/develop/files/static/js/dashboard/inventory.js#L36
So those two line should be removed.

The `dashboard.js` module will auto-detect tables with the `tablesorter` class added, and activate it.

**Comment by OptimusCrime** [comment]
Fixed pr c1ed5bdbc7e8b3f82c4b68f9da25cc93092e1efd
