### ISSUE TITLE
Wrong tag on website easy

### ISSUE THREAD

**Issue by thommath** [dotKom/onlineweb4#1645]
Wrong tag on "Medlemmer". 
Change from `<p>h2. Medlemmer</p>` 
to `<h2>Medlemmer</h2>`

https://online.ntnu.no/wiki/online/historie/dotkom/

**Comment by nornes** [comment]
Noe for de nye?

**Comment by thommath** [comment]
Høres ut som en god ide!

**Comment by sklirg** [comment]
Thanks for the issue report. :-)

This is now fixed.
