### ISSUE TITLE
Inventory add/edit fails with a validation error even though fields are filled out

### ISSUE THREAD

**Issue by sklirg** [dotKom/onlineweb4#1649]
Inputting this data
![screenshot 2016-08-25 14 50 57](https://cloud.githubusercontent.com/assets/5422571/17969645/6ce78988-6ad3-11e6-9faa-dcd9a6646854.png)

produces this result
![screenshot 2016-08-25 14 51 03](https://cloud.githubusercontent.com/assets/5422571/17969644/6ce256a2-6ad3-11e6-9106-9a56c6caf83d.png)

**Comment by nornes** [comment]
The same problem occurs when adding categories

**Comment by Aborysa** [comment]
Image uploader has conflicting name, causing invalid field value for "name"

**Comment by nornes** [comment]
Why would that affect category?
