### ISSUE TITLE
Wiki search function behaves strangely

### ISSUE THREAD

**Issue by MrWe** [dotKom/onlineweb4#1655]
--> Someone please rewrite this after reproducing. I'm not exactly sure how to explain it. <--

The search function returns the same instance of the word you are searching for multiple times. It also changes which results that are shown on specific pages based on which result you are shown on a previous page. 

Steps to reproduce: 

1. Search for a word. The entire first page should show the same instance. 
2. Navigate to a few different result pages, and then back to the first page. The results shown there should match the results you were just shown.

**Comment by nornes** [comment]
I can't seem to reproduce the bug no matter what I do.

**Comment by sklirg** [comment]
Could you re-open this if the bug is still present? Please provide us with more detailed steps to reproduce, for example the search query you used and from what page you searched.
