### ISSUE TITLE
Company thumbnail on event still use old thumb

### ISSUE THREAD

**Issue by chrlofs** [dotKom/onlineweb4#1664]
Tried to update the thumbnail on a company. The thumbnail on the main page is updated, but the thumb on the event still uses the old picture. 

<img width="592" alt="skjermbilde 2016-09-05 kl 10 10 46" src="https://cloud.githubusercontent.com/assets/9264978/18241375/10d7ae94-7351-11e6-8aa2-3e6ae1e65677.png">
<img width="483" alt="skjermbilde 2016-09-05 kl 10 10 55" src="https://cloud.githubusercontent.com/assets/9264978/18241376/10f39c8a-7351-11e6-8590-020315400043.png">

**Comment by OptimusCrime** [comment]
I'll take it from here @duvholt :)
