### ISSUE TITLE
attendees_not_paid property is plain wrong

### ISSUE THREAD

**Issue by duvholt** [dotKom/onlineweb4#1667]
It returns all attendees who have paid instead. It is only used for sending out emails afaik.

https://github.com/dotKom/onlineweb4/blob/2347446f5bb66d202b7adecc9433a8e26fe3b0b4/apps/events/models.py#L450

IMO it should be something like `return list(self.attendees.filter(paid=False))` instead of simply adding a `not`,

**Comment by OptimusCrime** [comment]
https://github.com/dotKom/onlineweb4/commit/7ee69ebc135131eb5742a99ad33ab2f5587ae35d#diff-3310307136147b680a88626a2444fbf8R439

**Comment by nornes** [comment]
Was this fixed?

**Comment by duvholt** [comment]
Nope
