### ISSUE TITLE
More intuitive headers for dashboard.careeropportunities

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#1687]
By clicking "Edit" on a Career Opportunity object in the dashboard, you get presented with the text "New Carreeropportunity" rather than e.g. "Update Careeropportunity". 

I guess there are more places in the dashboard this could be checked out, maybe even standardise it for all components in the dashboard.

**Comment by anneork** [comment]
@oleast Is this fixed? I cannot see any problem anymore.
