### ISSUE TITLE
include more details in payment receipts received per email.

### ISSUE THREAD

**Issue by myth** [dotKom/onlineweb4#1691]
As title says. Now it only says OK and an uuid which is nonsensical for the user.

**Comment by melwil** [comment]
There are several fields which are missing that are required to stipulate a valid receipt. Fields like sum paid, MVA and orgnr are needed to actually use the receipt for anything. While I am aware that there is a registry on the web page to view this, having an email with this information is way more handy.

If this is going to be improved, I suggest taking a look at this page:

https://www.altinn.no/no/Starte-og-drive-bedrift/Drive/Regnskap-og-revisjon/Hva-er-bokforingsplikt/Hva-skal-sta-pa-salgsdokumentene/

**Comment by OptimusCrime** [comment]
We do not pay MVA?
