### ISSUE TITLE
Automatically close captcha modal when captcha is verified

### ISSUE THREAD

**Issue by duvholt** [dotkom/onlineweb4#1698]
This should only happen if no other input is needed (phone number, accept "prikkregler" etc).

I suspect support has to be added to django-recaptcha, but the project is open source so I don't think that should be a problem.

**Comment by duvholt** [comment]
django-recaptcha supports the "new" invisible captcha which should make this much easier. 
However we can't just enable it as that would present a blank popup to the users which is confusing.

**Comment by plusk** [comment]
Neato, we'll take another look at captcha when we get to it on OWF.
