### ISSUE TITLE
Refactor careeropportunity

### ISSUE THREAD

**Issue by Westermoen** [dotKom/onlineweb4#1702]
TODO:
1. Get kravspec (@sklirg)
2. Involve prokom in design phase (on wait)
3. Rework code (in progress)

Features:
- [ ] Tags (location, type, maybe language/various)
- [ ] Integration to Django rest framework
- [ ] Redesign

Maybe:
- [ ] Redux/Angular 2
- [ ] Search

**Comment by OptimusCrime** [comment]
New field: type, location.

**Comment by OptimusCrime** [comment]
We have a project for this now. See https://github.com/dotKom/onlineweb4/projects/2
