### ISSUE TITLE
Links to company websites doesn't work without http:// 

### ISSUE THREAD

**Issue by nornes** [dotkom/onlineweb4#1718]
On a company profile page the link to the company's website will only redirect the user if `http://` is specified when the link is added in the dashboard. For example, the link to AppearTV is written as `www.appeartv.com`, and redirects to `https://online.ntnu.no/company/60/www.appeartv.com`.
There is no information to the user creating an event to add http either, so I can imagine this being a growing problem.

**Comment by sklirg** [comment]
Protocol should be included. Needs more validation. Double check if it is
an URLField.

**Comment by myth** [comment]
Tip: https://docs.djangoproject.com/en/1.10/ref/validators/#urlvalidator
Use Django's validators for things like these.

**Comment by duvholt** [comment]
Not using URLField was done deliberately: #695
I just checked though and none of the current URLs use markdown so it's safe to change back to URLField. 

IMO fields like these should be rendered using the [urlize](https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#urlize) filter.

**Comment by sklirg** [comment]
We can manually grab the hostname without the protocol if that's what that issue targets. This enables us to use the URLValidator.

ATM we hope the url field is a URL, and we create a href to the "webpage". Look at this: https://online.ntnu.no/company/19/.

Which is what this issue targets.

If it's an URL to be placed in the field, let it be validated by the URLValidator.
