### ISSUE TITLE
Unify URLs

### ISSUE THREAD

**Issue by OptimusCrime** [dotkom/onlineweb4#1723]
The URLs are messed up.

First of all, the URLs should be in norwegian as all the other content on our site is in norwegian. A link such as: https://online.ntnu.no/events/342/midtsemesterforelesning-i-algdat/ looks weird. It would make more sense if it was https://online.ntnu.no/arrangement/342/midtsemesterforelesning-i-algdat/ . Not to mention the fact that it says `events` as in plural.

The archives is lacking a structured pattern:
https://online.ntnu.no/events/
https://online.ntnu.no/article/archive/
https://online.ntnu.no/offline/

Karriere is also called `careeropportunity` which is also weird. Simply calling it `karriere` would be much better. Here slugs are missing too:
https://online.ntnu.no/careeropportunity/
https://online.ntnu.no/careeropportunity/85/

Same with company:
https://online.ntnu.no/company/4/

No idea why Ressurser is called RESSURSSENTER either. Why can it not be Ressurser? Senter just sounds lame.
https://online.ntnu.no/resourcecenter/

We should agree on a common pattern and stick to that. I for one vote for norwegian URLs + using /app/id/slug as the pattern everywhere.

**Comment by sklirg** [comment]
We should do this for the apps themselves as well, `apps.events` and `apps.article` etc.

This is more of a refactoring task and I don't think we can prioritize it _at the moment_ due to the sheer lack of work force.

**Comment by OptimusCrime** [comment]
Agreed to both. However, we should have a clear structure to follow to avoid these situations in the future.

**Comment by melwil** [comment]
Remember that if we do this, we need to put all the old links up as permanent redirects, or lose SEO ranking ;-)

**Comment by plusk** [comment]
This will be handled by OWF.
