### ISSUE TITLE
Dashboard improvements

### ISSUE THREAD

**Issue by Torrib** [dotkom/onlineweb4#1727]
General feedback and improvements suggestions on the current dashboard implementation.

I think that the attendee administration should be a bit more separated more from the event administration. I think that in most of the cases the users add the event (with attendance, feedback etc) once and then they are for the most part only interested in managing the attendees. I suggest moving attendees, waitlist, payment overview (only the summary over who's paid what) , reservations and extras overview to it's own page (kind of like the current implementation).

Couple of points the different views:

**General**
- [ ] Reservations missing
- [ ] Choosing times is a pain
- [ ] If multi-select, remember to write "Hold Cmd/Ctrl to select multiple", or use a better system
- [ ] Multi select boxes are too small (height wise)

**Attendance.** 
- [ ] Dates are not prefilled based on event date.
- [ ] "Waitlist" field should be true by default? (open for discussion)
- [ ] "Rule bundles" does not currently provide a very good overview over selected bundles.

**Feedback**
- [ ] Deadline not prefilled (Should be a week after event end)
- [ ] Should be possible to edit deadline date without removing and re-adding it.

**Payment**
- [ ] Type should be delay by default
- [ ] Deadline field should only be visible if the "deadline" type is selected
- [ ] Delay field should only be visible if the "delay" type is selected
- [ ] A bit unintuitive that the prices are only displayed after the payment has been added. 
- [ ] Price managing after a price has been added is a bit unintutive as well (hidden in a expandable view)

**Comment by plusk** [comment]
That's a whole lot of annoying frontend stuff that we'll make sure not to introduce when we write a new dashboard for OWF.
