### ISSUE TITLE
Make sure JS/CSS is ran through compressor

### ISSUE THREAD

**Issue by duvholt** [dotKom/onlineweb4#1732]
Compressor minifies files and make sure that changed resources like JS/CSS are not cached by the browser by using a hashed filename.

Files that contain `.min.js` are already minified and are likely libraries. No need to run them through compressor.

Example of compressor:
https://github.com/dotKom/onlineweb4/blob/c43de3acc27b6429352d88668b14d81ca85d6d2f/templates/gallery/index.html#L75

Example of file that needs to be fixed:
https://github.com/dotKom/onlineweb4/blob/d725049d5554b90adba718a1bafc98cecdc69646/templates/dashboard_base.html#L336

This has likely not been done correctly in many templates. 

Simple search for JS and CSS blocks:
https://github.com/dotKom/onlineweb4/search?utf8=%E2%9C%93&q=%22block+js%22++OR+%22block+styles%22&type=Code

**Comment by OptimusCrime** [comment]
How about we switch this for webpack or something in near future? No idea why the compression here is done serverside like this. Anyone in favor of switching this out for a more modern approach?

**Comment by duvholt** [comment]
>No idea why the compression here is done serverside like this

It was easy to configure for both production and development and worked good enough IMO.

>Anyone in favor of switching this out for a more modern approach?

Absolutely. This issue was meant more as a quick fix for the caching issues we have at the moment.
Replacing compressor with webpack requires a lot more work.

I think we should focus on getting one of the React components out in production first to get a feel on how hard it is to configure automatic building with webpack. Will hopefully happen on Wednesday.
