### ISSUE TITLE
Alter event permission text slightly

### ISSUE THREAD

**Issue by OptimusCrime** [dotKom/onlineweb4#1734]
Could be only me but "Du er ikke i et klassetrinn som har tilgang til dette arrangementet" sounds a bit weird. How about changing them around to "Du er i et klassetrinn som ikke har tilgang til dette arrangementet".

VERY FRIKKIN IMPORTANT PLS FIX

**Comment by Seagullible** [comment]
#1735

**Comment by sklirg** [comment]
I think the current wording is fine.
