### ISSUE TITLE
Handle Stripe errors

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#1785]
We're bad at handling Stripe errors. We should handle the appropriate errors for our actions rather than allowing them to cause runtime errors.

https://stripe.com/docs/api/python#errors

**Comment by plusk** [comment]
Closing this as a generally vague goal instead of a specific issue. Our [newer usages](https://github.com/dotkom/onlineweb4/blob/972069a2ec64b6050d721ca619c66904be54eb86/apps/payment/serializers.py#L53) of Stripe handle errors pretty alright
