### ISSUE TITLE
Make attendance event information in dashboard more intuitive

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#1814]
## What kind of an issue is this?

- [X] Feature request

## What is the expected behaviour?

Easily update information about the attendance event without having to struggle to find where to do this.

## What is the current behaviour?

It is not intuitive where to go to edit information about the attendance event.

## Other information

![image](https://cloud.githubusercontent.com/assets/5422571/22999679/1445784c-f3dd-11e6-81e9-5b5457316b2e.png)

**Comment by plusk** [comment]
We'll just make a better interface in OWF.
