### ISSUE TITLE
Show if inventory item is available in nibble shop in product listing

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#1815]
## What kind of an issue is this?

- [x] Feature request

## What is the expected behaviour?

There should be an icon in the dashboard product listing page that shows if an item is available for sale in Nibble.

This icon should also be clickable, to toggle whether or not the item should be available for sale in Nibble.

It should be possible to sort the items in the table according to the "available for sale"-state.

## Other information

This is how an event's attendee list looks, and it could probably be done in the same way (look at the rightmost column): 
![screenshot 2017-02-27 17 05 03](https://cloud.githubusercontent.com/assets/5422571/23368846/7f1a2600-fd0f-11e6-9499-7afeedf65f76.png)

This is to be done in this list:
![screenshot 2017-02-27 17 05 47](https://cloud.githubusercontent.com/assets/5422571/23368830/72016b18-fd0f-11e6-98f0-485ccebe14c7.png)

**Comment by oleast** [comment]
Solved in part by #2118 
But should add the rest of the requested functionality.

@R33an1 Didn't you start working on this?
