### ISSUE TITLE
Past events list is very slow to load

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#1821]
## What kind of an issue is this?

- [x] Bug report

## What is the expected behaviour?

The events list in the dashboard should load relatively quick.

## What is the current behaviour?

The events list in the dashboard is very slow to load, so slow that it looks like nothing is happening. Time to first byte is ~2 seconds.

## How do you reproduce this problem? 

Visit the "Tidligere arrangement" link in the events dashboard.

## Other information

This could be fixed by implementing pagination of the events overviews (both upcoming and previous).

**Comment by plusk** [comment]
hahahahha
owf
