### ISSUE TITLE
Not possible to unsubscribe from 'Infomail' mailing list in profile anymore

### ISSUE THREAD

**Issue by OptimusCrime** [dotkom/onlineweb4#1824]
## What kind of an issue is this?

- [x] Bug report
- [ ] Feature request

## What is the expected behaviour?

Unsubscribing from the 'Infomail' should remove the user from the mailing list. Using G-suite, this no longer happens.

## What is the current behaviour?

User is still subscribed to the 'Infomail' mailing list and receives the mails sent there. 

## How do you reproduce this problem? 

Unsubscribe from the 'Infomail' in your [personal profile](https://online.ntnu.no/profile/email/) and wait for the weekly mail to be sent. You should not get it in your inbox anymore.

## Other information

[Source code](https://github.com/dotkom/onlineweb4/blob/develop/apps/profiles/views.py#L418-L429) is pretty clear here. It correctly toggles the infomail flag on the user object, but this is not mirrored in the G-suite mailing list.

NOTE: This may very likely also be a problem with the jobmails.

**Comment by sklirg** [comment]
Bumped priority, this is important before next semester when we get a lot of new members.
