### ISSUE TITLE
Spelling mistake at jobmail in user profile

### ISSUE THREAD

**Issue by OptimusCrime** [dotkom/onlineweb4#1825]
## What kind of an issue is this?

- [x] Bug report
- [ ] Feature request

## Information

In [your profile under email settings](https://online.ntnu.no/profile/email/) the description for jobmail reads:

>Her kan du velge å få informasjon om diverse arrangement, oppdrag og småjobber **reltart** til informatikkstudiet.

**Comment by martinlunde** [comment]
Pull request #1844
