### ISSUE TITLE
Frontpage events look somewhat cramped at lower window sizes

### ISSUE THREAD

**Issue by sardred** [dotkom/onlineweb4#1849]
## What kind of an issue is this?

- [x] Isn't this what the type label is for? UI, anyways.

## What is the expected behaviour?
Good looking interfaces.

## What is the current behaviour?
Could use a whole lot more separation between events in the event (hehe) that there's no image. 

![image](https://cloud.githubusercontent.com/assets/14059677/25295965/4221cfc2-26e6-11e7-8f7b-7983296ce416.png)

## Other information
i love you guys.

**Comment by oleast** [comment]
Fixed by #2153
