### ISSUE TITLE
Make webshop great

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#1852]
## What kind of an issue is this?

- [x] Feature request

## What is the expected behaviour?

The webshop should provide useful and easy to use functionality for the users, both buyers and sellers.

## What is the current behaviour?

"There are some problems with the webshop dashboard" (?) Care to fill in, anyone with more knowledge? (@duvholt?)

The admin panel should have easy filtering on paid status as well as product so it's easy to filter out paid for orders for a given product.

## How do you reproduce this problem? 

Visit admin panel for webshop, or dashboard page for webshop.

**Comment by myth** [comment]
Skrøkkjås list of things that could be improved on the web shop:

* Landing page layout is quite bad. Lacking proper margins and grid. A suggestion would be to have a couple of featured articles that are "on sale" or by other request, and have smaller links to other stuff, like we do with articles or events.
* Categories should be listed directly on the web shop landing page. The fewer clicks to glory, the better.
* Crop ratio for product pictures need to be re-visited perhaps, or just start using the actual product aspect ratio images.
* I think the shopping cart link should be aligned (right floated) with the web shop title, so it is always on the same place. Maybe also display the sum total along with number of items in the cart.
* Maybe also advertise somewhere on the landing page that purchases are made with credit/debit card using Stripe
* The dashboard needs a total re-write. It's not much functionality there atm, but for starters, just copy pasting the same old table layout used on many of the other apps is perhaps not the best idea. Use additional sub-pages for "order dashboards" per item for instance, or some other means of grouping items and being able to present useful statistics at the same time.

**Comment by sklirg** [comment]
Also look at #1338.

**Comment by duvholt** [comment]
I think most of the frontend stuff should be completely rewritten.
It was more or less thrown together in a hurry to have something that worked just good enough to be used.

I will make a more detailed plan when I have time.

**Comment by sardred** [comment]
This is a bit besides the technical details, but it would be nice to give the user some indication of what's going on. Just used the shop for the first time and it really gives you no idea what the next step is after purchase. Do their people get in touch with my people? Plus, when having hit the purchase button, waiting for that confirming refresh is somewhat concerning.

**Comment by plusk** [comment]
The webshop will be completely rewritten for OWF, one day.
