### ISSUE TITLE
Mailto links don't work in articles and chunks

### ISSUE THREAD

**Issue by aslakhol** [dotkom/onlineweb4#1855]
## What kind of an issue is this?

- [x] Bug report
- [ ] Feature request

## What is the expected behaviour?
Mailto links should work

## What is the current behaviour?
Mailto links link to /# instead of opening email

## How do you reproduce this problem? 

Just look at any of the mailto links in the chucks, or in an article

**Comment by plusk** [comment]
This is a problem with our markdown renderer no longer allowing us to render mailto links without also allowing unsafe HTML, so it's a wontfix.
