### ISSUE TITLE
Linked data - because the internet needs it

### ISSUE THREAD

**Issue by niklasmh** [dotkom/onlineweb4#1856]
## What kind of an issue is this?

- [ ] Bug report
- [x] Feature request

## What is the expected behavior?

Adding a script tag in the HTML-pages telling what the search engines look at, and what other resources the site is linked to. We can add NTNU as an organization above us, making the onlineweb linked to NTNU in a form of structured data.

```javascript
<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Organization",
  "address": { ... },
  "description": "...",
  "email": "...",
  "image": "...",
  "name": "Online",
  "memberOf": {
    "@type": "Organization",
    "name": "NTNU",
    "url": "https://ntnu.no"
  },
  "sponsor": {
    "@type": "Organization",
    "name": "Sopra Steria",
    "image": "...",
    "url": "..."
  },
  "url": "https://online.ntnu.no"
}
</script>
```

This provides better search results and better visibility on the web. Tim Berners Lee also requests people to cope with this way of building the web in the future (ref. [TED-talk](https://www.ted.com/talks/tim_berners_lee_on_the_next_web)).

**Comment by sklirg** [comment]
> recent

> Filmed Feb 2009

Further reading: https://en.wikipedia.org/wiki/Semantic_Web

**Comment by OptimusCrime** [comment]
This is [TMM4230 ](http://www.ntnu.no/studier/emner/TMM4230/2011#tab=omEmnet)all over again. I still have nightmares of OWL and RDF :(

**Comment by duvholt** [comment]
:heart: OWL :heart:  RDF :heart: SparQL :heart: Swoogle :heart:

Seriously though I don't think this is worth the effort. 
If semantic web somehow actually becomes popular we can add it, but we're too small to have any influence over this.

**Comment by niklasmh** [comment]
~~Have we thought about it yet? I see we have meta tags, but those does not link to any structure, like [schema.org](http://schema.org/) provides. It may not help us much as an organization, but it is just an idea as this (Linked data) became a standard in 2012(?) at W3C (read at [W3C](https://www.w3.org/TR/2012/WD-ldp-20121025/), do not quote me on that too).~~

~~Maybe this can be discussed a little further with people who knows a little more about the concept.~~

Maybe it is too much effort. Seems like you know what I mean, but just a thought for the future. :)

**Comment by duvholt** [comment]
Oh, the idea itself is great, but IMO it's unlikely that the web as a whole will follow such a standard. 
I mean people barely manage to write working HTML code.

**Comment by niklasmh** [comment]
Nice to be a good example too, but if no one else does it either it would probably be a lost cause.
