### ISSUE TITLE
Support portrait images for articles

### ISSUE THREAD

**Issue by aslakhol** [dotkom/onlineweb4#1862]
## What kind of an issue is this?

- [x] Feature request

## What is the expected behaviour?

Prokom wants to be able to use portrait pictures in articles. We'll need to look at the image cropping and making a design for the articles that works with portraits.

**Comment by sklirg** [comment]
I'm tempted to say that this is a #wontfix, since it requires all articles to use portrait images or to make some custom rule regarding how to show all articles if one (or more) of them have portrait images.

**Comment by plusk** [comment]
Having both portrait and landscape images adds a layer of complexity to the frontend design of articles, which we are just not interested in. It's a fairly rare case where there's no kind of tweaking that can be done to make it work as a landscape image. We're closing this for now.
