### ISSUE TITLE
Send email to applicants when application is processed. 

### ISSUE THREAD

**Issue by chrlofs** [dotkom/onlineweb4#1864]
## What kind of an issue is this?

- [ ] Bug report
- [x] Feature request

## What is the expected behaviour?
When an applicant submits an application, he/she should receive an email with the result when the application is processed. 

## What is the current behaviour?

When the application is processed, the user receives no information about the result.

**Comment by sklirg** [comment]
This feature already exists and was introduced in #1708.

The feature was not switched on, but it is now.
