### ISSUE TITLE
Committee leader names' email links don't work

### ISSUE THREAD

**Issue by michaeljohansen** [dotkom/onlineweb4#1872]
## What kind of an issue is this?

- [x] Bug report
- [ ] Feature request

## What?

Steps to reproduce:
1) Go to https://online.ntnu.no/#!about/bedkom
2) Click name of committee leader (title text "Send epost til komiteleder")
3) It failed
4) Cry, cry a lot

**Comment by sardred** [comment]
Closing this as it is a duplicate issue. See #1855.
