### ISSUE TITLE
Can't find images on the wiki

### ISSUE THREAD

**Issue by kattn** [dotkom/onlineweb4#1884]
## What kind of an issue is this?

- [x] Bug report
- [ ] Feature request

## What is the expected behaviour?
The images should show when the guide to adding them to the wiki is followed

## What is the current behaviour?

There is only an empty frame with "Image not found" where the image should be, but it looks like the box has the right size of the images.

## Other information

https://online.ntnu.no/wiki/online/daljer/

A page with alot of images that should be seen.

**Comment by sklirg** [comment]
The images are there if you click on them, though.

@duvholt, did you find out anything regarding this?

**Comment by duvholt** [comment]
Bug in sorl-thumbnail: https://github.com/jazzband/sorl-thumbnail/issues/503

Going to apply workaround now.

**Comment by duvholt** [comment]
It works.
