### ISSUE TITLE
Update chunks: out with the old, in with the new

### ISSUE THREAD

**Issue by sardred** [dotkom/onlineweb4#1896]
## What kind of an issue is this?
- Fix plz

## What is the expected behaviour?
- Chunks that represent the current status of dotkom.

## What is the current behaviour?
- Chunks that don't represent the current status of dotkom.

## How do you reproduce this problem? 
- Look at chunks, and see that they don't represent the current status of dotkom

## Other information
![image](https://user-images.githubusercontent.com/14059677/30033081-5ad33308-9199-11e7-8c72-bc7274091984.png)
Remove all old people that aren't Katrine, move her up to active, and set Andrea as being on temporary leave

Also add the newcomers. Their names are as follows:
- Tor Berre
- Marius Tobiassen
- Kevin Midbøe
- August Solvang
- Mathias Brekkan
- Monika Muzyk
- Siddise Hirpa
- Herman Henriksen

**Comment by sklirg** [comment]
This is not a code thing with OW4 and should be done in dashboard instead
of through the code.

**Comment by sardred** [comment]
You are absolutely correct, but I was clearly instructed to leave it as an issue for the newcomers, instead of handling it myself.

**Comment by AslakHol** [comment]
The idea was to leave a super simple task for our new friends, so someone gets to touch the dashboard very quickly.

**Comment by sklirg** [comment]
I think we should rather use an [dotkom/issues](https://github.com/dotkom/issues) for this kind of issues rather than the public GitHub issue tracker, which is for code. Chunks can be edited at `/dashboard/chunks/` and has nothing to do with the code.

**Comment by OptimusCrime** [comment]
👍
