### ISSUE TITLE
Many users do not know about the infomail

### ISSUE THREAD

**Issue by aslakhol** [dotkom/onlineweb4#1904]
## What kind of an issue is this?

- [x] Enhancement

## What is the expected behaviour?
All users should be made aware of and encourage to subscribe to the infomail when creating an account. 

## What is the current behaviour?
About 0 first graders are signed up, and many express that they want the feature when they are told of it. 

## What do we do?
I believe the best course of action is to rework the account creation process and make this option much more obvious.

**Comment by AslakHol** [comment]
We agreed in the meeting that we should also look into sending a "Welcome to this list" email when people are added to it.

**Comment by sardred** [comment]
There's been some back-and-forth on this lately, what's the status @aslakhol?

**Comment by aslakhol** [comment]
Dotkom has decided that the email should stay opt-in. But we have committed to two measures to appease those who deal with the email. 
1. We will send an email to all first graders who are not currently signed up for the email telling them about the possibility. (This could be reconsidered to be another messaging tool as well.) 
2. We will rework the account creation process to make it much clearer that signing up for this email is an option and what benefits this and the opportunities email have. 

I'm renaming the issue.

**Comment by plusk** [comment]
We're moving onboarding to OWF, so this will be related to the #866 chunk of issues.
