### ISSUE TITLE
Add more API filters for attendance events

### ISSUE THREAD

**Issue by plusk** [dotkom/onlineweb4#1905]
## What kind of an issue is this?

- [x] Feature request
- [x] Procrastination
- [x] Checklist
- [ ] Helpful checklist

Would love to see some more options for filtering through the API, for example an option to filter and sort by registration start date.

**Comment by oleast** [comment]
Should be able to filter events by if a user can attend the event.

**Comment by oleast** [comment]
Events can now be filtered by:
- If the user can attend said event
- If the user is attending
- The companies co-hosting the event
- If the user has permission to change the event

**Comment by plusk** [comment]
What I really wanted was a page telling me when I can register for events with free dinner etc. I'm sure we'll make something like that in OWF, and we'll look into the backend when that time comes.
