### ISSUE TITLE
Payment after due date

### ISSUE THREAD

**Issue by FluidSense** [dotkom/onlineweb4#1916]
## What kind of an issue is this?

- [ ] Bug report
- [X] Feature request

## What is the expected behaviour?
To be able to pay for something that is already due, for example for events where the bill is sent to Online, but should be split among the participants.
This would also be a good solution to the problems that now arise if you want to follow the "prikkregler":
"Hvis avmeldingsfristen har gått ut vil man få en prikk, og vil ikke kunne melde seg på andre arrangementer før det utestående beløpet betales. ".

## What is the current behaviour?
You have to pay manually which is a lot of work for the economy comittee.

**Comment by henrikhorluck** [comment]
This is implemented with suspensions already?
