### ISSUE TITLE
Updating "My profile" does not save all profile fields

### ISSUE THREAD

**Issue by S1GGEN** [dotkom/onlineweb4#1938]
## What kind of an issue is this?

- [x] Bug report
- [ ] Feature request

## What is the expected behaviour?
Seeing my post number at my [profile overview page](https://online.ntnu.no/profile/overview/)

## What is the current behaviour?
Seeing `None Ugyldig postnummer` at my [profile overview page](https://online.ntnu.no/profile/overview/)

## How do you reproduce this problem? 

- Go to the [profile edit page](https://online.ntnu.no/profile/edit/), write `7050` (or another post number) into the _Postnummer_ field
- Press _Lagre brukerinformasjon_. No visible errors on page or in browser console, green status box at the top says _"Brukerprofilen din ble endret"_
- Go to the [profile overview page](https://online.ntnu.no/profile/overview/), look for the _Adresse_. You should now see `None Ugyldig postnummer`.

### Screenshots
[Profile edit page:](https://online.ntnu.no/profile/edit/)
![image](https://user-images.githubusercontent.com/12127271/32372177-150971b4-c094-11e7-8a05-01eee0603e30.png)
[Profile overview page:](https://online.ntnu.no/profile/overview/)
![image](https://user-images.githubusercontent.com/12127271/32372269-6b2cfdea-c094-11e7-9b39-a459a86451dd.png)

**Comment by sklirg** [comment]
I suggest you move to a place with a valid zip code.

**Comment by sklirg** [comment]
Okay, the issue has been identified and we'll fix it.

The problem is that the `post_code` field in the "My profile"-form is not stored when the form is submitted.
