### ISSUE TITLE
Restrict access to globalhistory wiki plugin

### ISSUE THREAD

**Issue by AslakHol** [dotkom/onlineweb4#1946]
## What kind of an issue is this?

- [ ] Bug report
- [x] Feature request

## What is the expected behaviour?
Only superusers should be able to access the wiki history

## What is the current behaviour?
Anyone can access the page, and the plugin filters articles you can view based on permissions. However the filtering is too inefficient, so we must restrict access.  

## Other information

We'd like to find a way to do this with Django

**Comment by sklirg** [comment]
I don't think we only want superusers to access it.

We'd like to control who can access it until django-wiki fixes is sub par filtering.

**Comment by duvholt** [comment]
The super slow filtering is fixed in the next django-wiki release.
