### ISSUE TITLE
Users get a mark for non-payment of event

### ISSUE THREAD

**Issue by aslakhol** [dotkom/onlineweb4#1949]
## What kind of an issue is this?

- [x] Bug report
- [ ] Feature request

## What is the expected behaviour?
Users should get booted from the event, which they are. But they should not get a mark. 

## What is the current behaviour?
They get a mark and get booted from the event. 

## Other information
The correct rules are outline here: https://online.ntnu.no/profile/marks/

**Comment by sklirg** [comment]
You shouldn't *always* get booted from an event if you haven't paid.

Follow the mark rules when fixing this issue.

**Comment by henrikhorluck** [comment]
We have new mark rules
