### ISSUE TITLE
Better feedback in dashboard when creating a careeropportunity

### ISSUE THREAD

**Issue by Westermoen** [dotkom/onlineweb4#1956]
## What kind of an issue is this?

- [x] Bug report
- [x] Feature request

## What is the expected behaviour?
Have better feedback in the dashboard when failing to create a careeropportunity

## What is the current behaviour?
Little or no feedback when failing to create a careeropportunity

## How do you reproduce this problem? 
Insert wrong data or break the rules defined for one of the input fields

**Comment by oleast** [comment]
Fixed by #2144
