### ISSUE TITLE
Tor has not drinken julebrus, on the very last dotkom-møte of the year!

### ISSUE THREAD

**Issue by tor0405** [dotkom/onlineweb4#1958]
## What kind of an issue is this?

- [ x] Bug report
- [ ] Feature request

## What is the expected behaviour?
Should have drunken julebrus

## What is the current behaviour?
anger

## How do you reproduce this problem? 
ask tor

**Comment by henricson** [comment]
Pls be on topic Tor. This is a serious organization, and this sort of "jokes" is inappropriate. I ask you to leave this repo.

**Comment by s0lvang** [comment]
"jokes" ARE inappropriate.

**Comment by tor0405** [comment]
After a dangerous and lonely journey down to the scary cellar, I have single handedly fetched, and consumed a bottle of the precious julebrus. During my travels, I have learnt a lot. Firstly, the cellar require a bottled key, which is incredibly exciting. I have also reflected extencivly and decided it would be best to outsource the further investigation of how such a situation could occur, to either the office-bot, or AI. Big data or Blockchains are also candidates for this.
