### ISSUE TITLE
Cake! 🎂  ❤️ 

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#2000]
🎂

**Comment by s0lvang** [comment]
We'll do this when getting to #1209 :-)

**Comment by FredrikAugust** [comment]
@s0lvang where's my cake? :angry:

**Comment by monikahm** [comment]
We the captain now

**Comment by plusk** [comment]
![78057191_624708608066078_1902619436376915968_n](https://user-images.githubusercontent.com/14059677/69259578-c5e48100-0bbe-11ea-898d-ad7c05398080.jpg)
