### ISSUE TITLE
Søke i arrangementsarkivet

### ISSUE THREAD

**Issue by didrikpa** [dotkom/onlineweb4#2011]
## What kind of an issue is this?

- [x] Bug report
- [ ] Feature request

## What is the expected behaviour and what is the current behaviour?
Hvis jeg søker på et arrangement, og tar vekk at det bare skal være fremtidige arrangementer, trykker på et arrangement, og går tilbake, forventer jeg at "bare fremtidige arrangementer"-funksjonen skal fungere som normalt, men den er reversert.

## How do you reproduce this problem? 

1. Gå på online.ntnu.no
2. Trykk på arkiv oppe til høyre
3. skriv inn et søkord, for eksempel "økonomi", og ta vekk at bare fremtidige arrangementer skal vises.
4. Når arrangementer har lastet, trykk på et arrangement
5. Gå så tilbake til arkivsiden og gjør steg 3. og 4. igjen.
6. Hvis man krysser/krysser ut bare fremtidige arrangementer nå, vil den ha motsatt effekt av det man tror den har.

## Other information

https://puu.sh/z2NDH/5fa0543e26.png -> Dette er ikke fremtidige arrangementer.

**Comment by sklirg** [comment]
Thanks for the detailed bug report!

I'm pretty sure this is a duplicate of #1074, so I'll close this in favour of that one.

**Comment by sklirg** [comment]
I also bumped the priority of it, so it'll be looked at quicker.
