### ISSUE TITLE
Fix GDPR

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#2015]
## What kind of an issue is this?

- [x] Feature request

## What is the expected behaviour?

Comply with GDPR.

Need to find out all of what we have to do to comply and how we want to do it.

## Other information

Some useful links.

https://www.eugdpr.org/
https://www.datatilsynet.no/regelverk-og-skjema/veiledere/hva-betyr/

**Comment by plusk** [comment]
This is mostly a discussion issue, which we've talked about ever since it was made. We're working on a larger project (a bit late, yeah) which will handle it, and smaller issues will be made for that in turn.
