### ISSUE TITLE
"Show attendees"-button does not show on events you cannot attend

### ISSUE THREAD

**Issue by MrWe** [dotkom/onlineweb4#2028]
## What kind of an issue is this?

- [x] Bug report
- [ ] Feature request

## What is the expected behaviour?
"Show Attendees"-button is shown on all social events. 

## What is the current behaviour?
"Show Attendees"-button is shown on only social events where the user can sign up for the event. 
The attendees list is still in the HTML, but not shown on the page. 

## How do you reproduce this problem? 

Enter an event where you cannot sign up, for example an event for 5. graders from a user in the 4. grade. 

## Other information

<img width="459" alt="screenshot 2018-03-05 22 18 19" src="https://user-images.githubusercontent.com/6748603/37000323-5bc7b810-20c3-11e8-88fe-e4d489538be3.png">
<img width="459" alt="screenshot 2018-03-05 22 18 27" src="https://user-images.githubusercontent.com/6748603/37000324-5beb3da8-20c3-11e8-946d-d1b2e21e780d.png">

**Comment by sklirg** [comment]
Hi,

Thanks for this issue. This is quite critical, and in the future we'd prefer if information about issues like these were sent privately by email.

**Comment by sklirg** [comment]
Fixed in #2031 and #2033.
