### ISSUE TITLE
Facebook sometimes does not preview images

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#2047]
## What kind of an issue is this?

- Bug report

## What is the expected behaviour?

When sharing an event on Facebook the image should be attached to the post.

## What is the current behaviour?

Sometimes the image is not displayed.

## How do you reproduce this problem? 

* Create a new post
* Link to an event on online.ntnu.no
* Wait for the preview to be generated
* Sometimes it does not work.

## Other information

One event that does not work is [this one](https://online.ntnu.no/events/507/ekskursjon-til-kid-bedrifter-i-trondheim/).
Another similar event that does work is [this one](https://online.ntnu.no/events/509/bedriftspresentasjon-med-netlight-2-4-klasse/).

The [Facebook sharing debugger](https://developers.facebook.com/tools/debug/og/object/) show images for both.

The scraper warns about no `og:image` tag (http://ogp.me/), which might be a start.

**Comment by plusk** [comment]
We'll see if it's still an issue with OWF.
