### ISSUE TITLE
Consider serving JS dependencies locally

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#2054]
## What kind of an issue is this?

- Enhancement (suggestion)

## Other information

The jQuery CDN was recently misconfigured for SSL/TLS (https://github.com/jquery/codeorigin.jquery.com/issues/34), which resulted in pretty much nothing working on our site due to it expecting a global jQ object to work with.

Even though we are moving away from jQ, I suggest serving the jQ lib locally so we can avoid issues like this in the future. This should be quite a quick fix to solve a potentially massive problem, if it ever happens again.

To reproduce/simulate the problem, load the webpage and block the request from `code.jquery.com`. 
This can be done in Chrome by going to Developer Tools -> Network -> right click the script loading from code.jquery.com and click "Block request URL".

**Comment by taplar** [comment]
You might also be interested in the hybrid alternative of: https://stackoverflow.com/questions/1014203/best-way-to-use-googles-hosted-jquery-but-fall-back-to-my-hosted-library-on-go

Allowing you to benefit from a CDN, but having a backup in case the occasional hiccup happens.

**Comment by sklirg** [comment]
Thanks for the tip, @taplar! Will definitely take that into consideration, bringing the best of both worlds. :-)
