### ISSUE TITLE
Dates fields in Dashboard are sorted alphabetically

### ISSUE THREAD

**Issue by oleast** [dotkom/onlineweb4#2067]
## What kind of an issue is this?

- Bug report

## What is the expected behaviour?
Dashboard lists should sort Date fields as dates.

## What is the current behaviour?

Dates fields in Dashboard tables are sorted alphabetically by the formatted Date. (`Do MMM YYYY hh:mm`)

## How do you reproduce this problem? 

Look at a list in the Dashboard, [example](https://online.ntnu.no/dashboard/webshop/orders/).
Click at the `Tidspunkt` column to sort by Date.
Bask in the glory of alphabetical sorting.

**Comment by hernil** [comment]
`order.datetime | date:"Y-m-j" `
Should do the trick afaik.

**Comment by sklirg** [comment]
That will change the date formatting. It should be possible to ask the sorting function to convert the "readable date" to an actual date, sort that date, and keep the text the same.

**Comment by hernil** [comment]
`YYYY-MM-DD` is by far the most readable way to format dates in my opinion. 

Also, obligatory: https://xkcd.com/1179/ :smiley:
