### ISSUE TITLE
Changing primary email address should change email address used for list subscriptions

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#2068]
## What kind of an issue is this?

- Bug report

## What is the expected behaviour?

If I change my primary email address I expect the mailing list services to be updated with my new address, whilst removing my old address.

## What is the current behaviour?

The old address is not removed and the new address is not added.

## How do you reproduce this problem? 

* (Add a new email to an account) (_Only required if there is no alternative email added to the account already_)
* Set the new email address as the primary
* _Notice that the action happens immediately_
    * (Vs. unsubscribing / subscribing to a list, which queries the mailing list service to add/remove addresses.)
* Verify that the old primary address is still on the list
* Verify that the new primary address is absent from the list

## Other information

The settings page tells the user that the primary address is the one used for mailing lists:

> **Adressen som er markert som primær brukes til alle våre e-postlister**, gjenoppretning av passord og andre varsler som sendes fra oss.

The [`set_primary`](https://github.com/dotkom/onlineweb4/blob/v4.24.28/apps/profiles/views.py#L326) function does not handle subscribing/unsubscribing to a list. (Neither does the [`Email model`](https://github.com/dotkom/onlineweb4/blob/v4.24.28/apps/authentication/models.py#L278) nor any signals attached to it.)

**Comment by sklirg** [comment]
Additional information: 

Because this sync has not worked since the fall of 2016, any person who tries to unsubscribe with an "invalid" email address should be informed about this change (look out for error codes from the Google API saying that this email address is not found), and prompt the user to either

* unsubscribe directly through the email, or
* switch back to the original email address as primary, unsubscribe from list, change back to current

Furthermore, this could also make it so that people who subscribed to the list with one address, changed their primary address (thought they) unsubscribed, then changed back, can experience an error where the API responds that this address is already on the list. (If that is the case, we should just silently update the checkbox state/database state and tell the user it succeeded.)

**Comment by plusk** [comment]
Hacky fix: unsubscribing, changing primary, then resubscribing programmatically :smiling_imp:
