### ISSUE TITLE
Articles dashboard page redirects to login instead of sending 403

### ISSUE THREAD

**Issue by torjusti** [dotkom/onlineweb4#2075]
## What kind of an issue is this?

- Bug report

## What is the expected behaviour?

If you attempt to visit the articles-path in the dashboard without the required permissiosn, you should receive a 403 error.

## What is the current behaviour?

You're redirected to the login page.

## How do you reproduce this problem? 

Attempt to visit https://online.ntnu.no/dashboard/article/ without the required permissions. You will be redirected to the login page. You can also find the link on the dashboard home page, in the recently activated modules section - this probably shouldn't happen, either :)

## Other information

This is probably due to decorators being used in the article views without setting flags correctly.

**Comment by sklirg** [comment]
Looks like a really simple fix. Add `raise_exception` to the permission required decorator, as detailed here: https://docs.djangoproject.com/en/2.0/topics/auth/default/#the-permission-required-decorator
