### ISSUE TITLE
Some NTNU usernames are too long

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb4#2093]
## What kind of an issue is this?

- Bug report

## What is the expected behaviour?

Any NTNU username should be allowed.

## What is the current behaviour?

Some people at NTNU can get usernames longer than our [10 character limit](https://github.com/dotkom/onlineweb4/blob/develop/apps/authentication/models.py#L144), which won't be allowed by our database backend. This makes it impossible for them to automatically register through Dataporten.

## How do you reproduce this problem? 

Try to set the NTNU username to something longer than 10 chars.

## Other information

This recently happened for someone with a work affiliation towards NTNU, which might happen if someone has worked at NTNU before becoming a student or something the like.

They will also have a stud account (which works), so we might need to inspect a data dump from such a user account to find a potential workaround, or we could increase the allowed size of NTNU usernames (however, then the `@stud.ntnu.no` email address might not work for that username?).

Maybe we should ask NTNU IT about this case.

**Comment by oleast** [comment]
We have looked though the NTNU LDAP, and asked Orakeltjenesten.
The consensus is that 50 characters would be an appropriate length for this field.

**Comment by aslakhol** [comment]
resolved in #2159
