### ISSUE TITLE
List of Events

### ISSUE THREAD

**Issue by Virkz** [dotkom/onlineweb4#2110]
## What kind of an issue is this?
- Feature request

## What is the expected behaviour?
Near the events part of the page a list or a button that redirects to a list of events that you are signed up for.

ical export would be nice

**Comment by sklirg** [comment]
The events archive already has this. See the link in the header for "Arkiv", make sure you're logged in and select "Mine arrangementer". As shown in this screenshot, you can export (to ical) a list of all events or the events you are attending.

![image](https://user-images.githubusercontent.com/5422571/45653784-7e092c00-bad9-11e8-8ac3-067214db2006.png)
