### ISSUE TITLE
Social members are able to attend events with GradeRules

### ISSUE THREAD

**Issue by oleast** [dotkom/onlineweb4#2112]
## What kind of an issue is this?

- Bug report

## What is the expected behaviour?

Social members should not be able to attend events without specifying the 'Sosialt medlem' rule bundle.

## What is the current behaviour?

Social members are allowed to attend events with grade rules.

## How do you reproduce this problem? 

Create an event with RuleBundles for grades 1-5.
Get a member with field_of_study as 'Social Member' to attend the event. 

## Other information

We think this is caused by social members have the `year` (OnlineUser.year) property set to `1`. This results in the social member being counted as a first-year student, which makes them eligible for attending Events with RuleBundles containing a GradeRule for first-year students.

The proposed change is to set the `length_of_field_of_study` for social members to return `0`. [As seen here](https://github.com/dotkom/onlineweb4/blob/c28b6e79f73bf98c5b2d6828aacb4cc3b605ee98/apps/authentication/models.py#L79-80)
This would make social members work as intended, by only letting them attend to events which specifically allow social members with their RuleBundle.

Would also like a few tests for this, to make errors like this harder to make.

**Comment by Chaaarles** [comment]
Resolved in #2116
