### ISSUE TITLE
psycopg2 dependency will soon be deprecated; change name

### ISSUE THREAD

**Issue by FredrikAugust** [dotkom/onlineweb4#2113]
## What kind of an issue is this?

* [x] Bug report
* [ ] Feature request

The `psycopg2` package will be renamed to `psycopg2-binary` in the coming `2.8` release, so consider changing the name in `requirement-prod.txt`. Read more [here](http://initd.org/psycopg/docs/install.html#binary-install-from-pypi).

**Comment by henrikhorluck** [comment]
This has been fixed in https://github.com/dotkom/onlineweb4/commit/5c1ee308af55d17926933a0ebf321eae76af3c35#diff-2e956cb3a96c63e8357b8ea2bfc22430
