### ISSUE TITLE
Users who are retaking their third year are automatically set to first grade

### ISSUE THREAD

**Issue by aslakhol** [dotkom/onlineweb4#2127]
## What kind of an issue is this?

- Bug report
- Feature request

## What is the expected behaviour?
Users who are retaking their third year and apply for an extended membership should be put in the third grade. This should happen when using the dataporten application. 

## What is the current behaviour?

Users who are retaking their third year are automatically set to first grade when using the automatic application system.

## How do you reproduce this problem? 

* Be doing extra year of informatikk after third year. 
* Use automatic membership application to extend your membership. 
* Cry.

**Comment by sklirg** [comment]
When this was implemented it was intentionally left out to require manual intervention for people who are on their "3+" year(s). If this is not the desired behavior, however, feel free to change it.

**Comment by aslakhol** [comment]
As long as the students are still students at BIT they should automatically be approved.
