### ISSUE TITLE
We need better logging of people being removed from events. 

### ISSUE THREAD

**Issue by aslakhol** [dotkom/onlineweb4#2128]
## What kind of an issue is this?

- Bug report

## What is the expected behaviour?
We need to know who removed a person, which person and what time. 

## What is the current behaviour?
We don't quite know what we have logged.

**Comment by sklirg** [comment]
I'd suggest also implementing an email notification to the organizing committee if a person is unattended after the `unattend_deadline`.

**Comment by oleast** [comment]
Fixed by #2138

**Comment by aslakhol** [comment]
Does #2138 log when users are removed from events through the adminpanel? @martinlunde

**Comment by martinlunde** [comment]
Unfortunately no, however the option of deleting attendees is removed from the adminpanel, so it should not cause any problems.
