### ISSUE TITLE
"Back to article link" from comitee wiki when permission is denied, doesn't work

### ISSUE THREAD

**Issue by jabrobak** [dotkom/onlineweb4#2145]
## What kind of an issue is this?
- Bug report

## What is the expected behaviour?
The "back to article" button should take the user the previous page: https://online.ntnu.no/wiki/ ?

## What is the current behaviour?
The "back to article"-button just refreshes the page.

## How do you reproduce this problem? 
When entering wiki for comitees, and permission is denied (because not member of a comitee?),and clicking "back to article"

**Comment by duvholt** [comment]
This is an issue with django-wiki. I opened an issue for the project here: https://github.com/django-wiki/django-wiki/issues/914

**Comment by oleast** [comment]
This has been fixed in django-wiki and was released in version 0.4.0.

Should be able to just upgrade from django-wiki 0.3.1 to 0.4.x.
However, the upgrade will be required for Django 2.
The upgrade to Django 2 has been started at #2156

**Comment by oleast** [comment]
We upgraded to Django 2 and Django Wiki 0.4.1.1 on November 19th.
This should be fixed now 😄
