### ISSUE TITLE
Unexpected form parameter when creating new poster 

### ISSUE THREAD

**Issue by FredrikAugust** [dotkom/onlineweb4#2154]
As reported by sentry:

```
Internal Server Error: /admin/posters/poster/

FieldError at /admin/posters/poster/
Cannot resolve keyword 'category' into field.
```

As reported: `reason = 'Jeg søkte etter 2 og fant 500 i stedet'`

Presume this is due to a form POSTing a field param that's not accounted for. Should be a quick and easy fix.

**Comment by sklirg** [comment]
Poster order creation is supposed to be done through the dashboard, the
admin part is simply nice to have. (or would be, if it worked)

**Comment by oleast** [comment]
Error was when searching poster orders, not when creating.
Probably still relevant to be able to search for them in admin :man_shrugging:
