### ISSUE TITLE
Remove list of email addresses from mail-participants page.

### ISSUE THREAD

**Issue by aslakhol** [dotkom/onlineweb4#2182]
## What kind of an issue is this?

- Enhancement
- GDPR

## What is the current behaviour?
On the mail-participants page for an event we list all the email adresses of attendees. This leads to issues in events with a lot of attendees since the list becomes so long that it is no longer obvious that we have a form for sending email at the bottom. 

There is also no reason for this page to display the email adresses and we should be limiting this information where we can, to be more compliant with behaviour. 

## What is the expected behaviour?
The page should not display a list of all email, it should only display the form for sending email. 

We could consider to list attendees here, but I think that would be unnecessary as they are listed in other places. 

## How do you reproduce this problem? 

Go to mail-participants page for an event.

https://online.ntnu.no/events/mail-participants/597

**Comment by oleast** [comment]
Fixed by #2204
