### ISSUE TITLE
Add ability to include images in emails sent from OW.

### ISSUE THREAD

**Issue by aslakhol** [dotkom/onlineweb4#2183]
## What kind of an issue is this?

- Feature request

## What is the expected behaviour?
We would like to be able to include images in email sent to participants of events.

## What is the current behaviour?
You can't and as such some emails are sent manually, not using the system.

**Comment by kharann** [comment]
Is it ok to have the mail as an attachment fine? Or do you wish the image to be shown in the mail

**Comment by oleast** [comment]
Fixed by #2228
