### ISSUE TITLE
Contribution app v2

### ISSUE THREAD

**Issue by martinlunde** [dotkom/onlineweb4#2185]
## What kind of an issue is this?
- Feature request

## Improvements OW4
- [x] Migrate from github REST to GraphQL
- [x] Setup oauth to increase allowed request limit
- [ ] Generate api token using dotkom github account 
- [x] Compare contributors from each repo to dotkom members to find external contributors
- [ ] Create new "hall of fame" api endpoint for owf (List of contributors can be incorporated into the new modals)
- [ ] model field for manually disabling repositories
- [ ] Fetch statistics from repositories and create endpoint for "repo activity data"

## Improvements OWF
- [ ] Implement pagination to see more than the top 10 repos. (Infinite scroll would not make sense, as the footer should be easily available)
- [ ] Create modals; Instead of linking directly to github repo, open modal with data.
- [ ] Fill modal with link to repository, repo name, version number and hall of fame.
- [ ] Create graphs displaying the "repo activity data" in a fashionable way.
- [ ] Implement badges; When certain criteria is met, the repos should get badges to be more visible in the list. (This could be e.g. "most activity🥇", "Needs attention 💔 " or "On a PR spree🔥")

## Suggestions
- Connect github user to an online user, so that users can get "stickers" on their profile ("achievements") if they have contributed to a repository.

**Comment by martinlunde** [comment]
[W.I.P.] https://github.com/dotkom/onlineweb4/tree/contrib_v2

**Comment by oleast** [comment]
I got a comment from a user that it is a bit confusing which repositories are displayed.
The problem was that `mysterious-powerking-conspiracy`, `Nibble2`, and the original `nibble` are all displayed because they were all changed recently.

Maybe we should have the capability to 'disable' some repositories from view?
