### ISSUE TITLE
Send mail from a committe to the participants

### ISSUE THREAD

**Issue by Paalar** [dotkom/onlineweb4#2186]
Send email to the participants of an event

## What kind of an issue is this?
- Feature request

## What is the expected behaviour?
Be able to send mail from Trikom (or other committees)

## What is the current behaviour?
Currently only possible to send mail from the mails in the picture.
Maybe automatically set it to the committee that arranges the event.

## Other information
<img width="553" alt="screenshot 2018-11-26 at 12 57 02" src="https://user-images.githubusercontent.com/22390745/49013142-019b6500-f17c-11e8-8424-716799192410.png">

**Comment by sklirg** [comment]
I'm guessing this could be refactored into simply emailing from the organizing committee rather than having to select who sends the email.

**Comment by oleast** [comment]
OnlineGroups have a field for email, so using that would work

**Comment by petterroea** [comment]
I would appreciate if it defaulted to the email corresponding to the commitee you are part of, it is easy to forget to select the correct email if you are in a hurry
