### ISSUE TITLE
Add loading message for requests that take time

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb4#2224]
## What kind of an issue is this?

- Feature request

## What is the expected behaviour?
So far only money-deposit and adding and removing to e-mail-list under "Min side" have this great feature, but it would be very useful if the group-page in Dashboard as well.

List of stuff that should have it that may or may not have it atm:
Ting jeg kommer på i farten:
- Everything related to payments
- Events
- Webshop (when writing in card info, more specifically after submitting the Stripe form, and waiting for OW4 to reload)
- Dashboard-> groups
- Others

## What is the current behaviour?
There is no loading message when doing said stuff

## Other information
This is added by using this https://github.com/dotkom/onlineweb4/pull/2071/files#diff-2b521f284d861d045490e79d2d5fea53

**Comment by oleast** [comment]
While I see the benefit of having this, I suspect the most critical parts this relates is Payments, which have been moved out of this front-end entirely.

- Event-signup can wait until OWF implementation.
- Groups should be good by now because of Celery.
