### ISSUE TITLE
Add support for Apple Pay and Google Pay with Stripe

### ISSUE THREAD

**Issue by chrlofs** [dotkom/onlineweb4#2230]
## What kind of an issue is this?

- Feature request

## What is the expected behaviour?

You can pay with Google and Apple pay on Stripe transactions. 

## Other information

Add the functionality to pay with Apple Pay or Google Pay on Stripe payments. There are no extra costs of doing this and it should be quite easy to do.

https://stripe.com/docs/apple-pay
https://stripe.com/docs/google-pay

https://stripe.com/docs/stripe-js/elements/payment-request-button

**Comment by oleast** [comment]
One can argue if it was easy to do, but it has been implemented as a working part for adding money to use in Nibble at https://beta.online.ntnu.no/payments

We are working on adding payments for the other parts of the application, and this will work for those as well. I'll consider this as completed.

Resolved by: https://github.com/dotkom/onlineweb-frontend/pull/266
