### ISSUE TITLE
Change article author to relate to OnlineUsers

### ISSUE THREAD

**Issue by oleast** [dotkom/onlineweb4#2237]
## What kind of an issue is this?

- Feature request

## What is the expected behaviour?

Article authors should be an OnlineUser, or a list of OnlineUsers.

This would make it easier to show information about the author(s).
Could also let us link to a users articles in their profile.

## Other information

Feature request for articles in Onlineweb Frontend

**Comment by henrikhorluck** [comment]
When working on this it would be nice if we add "flavour text" about the author, both on the author, and on the article, so if the article doesn't have one specified, it will default to the one on the author
