### ISSUE TITLE
Frontpage shows wrong image for event

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb4#2241]
## What kind of an issue is this?

- Bug report

## What is the expected behaviour?
The frontpage shows the correct image

## What is the current behaviour?
One of the images might swap out for the company image form a event you just looked on the detailpage of

This has happened twice for me today, on Safari on iOS (latest version, 12.2)

## How do you reproduce this problem? 
I have been unable to find a guaranteed way to reproduce it, but as far as I see it involves:
- Go to frontpage (current one)
- Go to "Avenger's Endgame"
- Go back to the frontpage
- Observe that the image for X-sport Cageball being swapped out with the image for the company attached to the "Avenger's Endgame"

## Other information
I was logged in at the time

![image](https://user-images.githubusercontent.com/36937807/56462696-ce29d300-63c7-11e9-8e66-916116cf7651.png)

**Comment by oleast** [comment]
I cannot see at all how this is possible without some kind of strange cache-problem occurring?

Events fetched from the API simply won't get images from other events.
