### ISSUE TITLE
offlines.length is undefined in assets/frontpage/OfflineWidget

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb4#2243]
Appears to only happen on mobile /Safari on macOS

Probably an issue that could be resolved with async/await
https://github.com/dotkom/onlineweb4/blob/d954a020b1fc7aaabac81c31384d78b2b095ad80/assets/frontpage/OfflineWidget.js#L32

https://sentry.io/organizations/dotkom/issues/356278432/?project=204971&referrer=github_plugin

```
TypeError: n is undefined
  at OfflineWidget (./assets/frontpage/OfflineWidget.js:32:5)
  at func (./assets/frontpage/OfflineWidget.js:59:5)
```

**Comment by sklirg** [comment]
Could probably be fixed alongside #2218.
