### ISSUE TITLE
Possible circular dependency in Authentication

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb4#2276]
https://sentry.io/organizations/dotkom/issues/1049751787/?referrer=github_plugin

```
ImportError: cannot import name 'OnlineUser' from 'apps.authentication' (/srv/www/onlineweb4/onlineweb4/apps/authentication/__init__.py)
  File "python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>

ImportError: cannot import name 'OnlineUser' from 'apps.authentication' (/srv/www/onlineweb4/onlineweb4/apps/authentication/__init__.py)
```

**Comment by oleast** [comment]
As you can see in the additional information of the Sentry data this was done through the Django shell.

Judging from the import being incorrectly written, I can tell you that this stems from me failing at importing  OnlineUser when fixing something in the shell 😄
