### ISSUE TITLE
Resizing the window when you have a chunk open causes a syntax error

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb4#2299]
https://sentry.io/organizations/dotkom/issues/1028035619/?referrer=github_plugin

```
Error: Syntax error, unrecognized expression: about/dotkom
  at error (/jquery-2.2.4.min.js:2:12565)
  at tokenize (/jquery-2.2.4.min.js:2:18614)
  at select (/jquery-2.2.4.min.js:2:21418)
  at fa (/jquery-2.2.4.min.js:2:7144)
  at find (/jquery-2.2.4.min.js:2:23936)
...
(6 additional frame(s) were not displayed)
```

**Comment by henrikhorluck** [comment]
Sentry issue: [ONLINEWEB-4-VD](https://sentry.io/organizations/dotkom/issues/1020028718/?referrer=github_plugin)

**Comment by henrikhorluck** [comment]
Sentry issue: [ONLINEWEB-4-W0](https://sentry.io/organizations/dotkom/issues/1050130815/?referrer=github_plugin)

**Comment by henrikhorluck** [comment]
Sentry issue: [ONLINEWEB-4-VP](https://sentry.io/organizations/dotkom/issues/1029188175/?referrer=github_plugin)

**Comment by henrikhorluck** [comment]
Sentry issue: [ONLINEWEB-4-VS](https://sentry.io/organizations/dotkom/issues/1038881832/?referrer=github_plugin)

**Comment by henrikhorluck** [comment]
Sentry issue: [ONLINEWEB-4-WY](https://sentry.io/organizations/dotkom/issues/1170480532/?referrer=github_plugin)

**Comment by henrikhorluck** [comment]
Sentry issue: [ONLINEWEB-4-X3](https://sentry.io/organizations/dotkom/issues/1188435712/?referrer=github_plugin)

**Comment by sklirg** [comment]
I'd rather merge the Sentry issues than linking 100s of them (=

**Comment by henrikhorluck** [comment]
You can 😮 TIL
