### ISSUE TITLE
Expand allergies to include diet

### ISSUE THREAD

**Issue by plusk** [dotkom/onlineweb4#2314]
**Describe the bug**
Right now, we only describe "allergier" in the user profile field for allergies and food preferences. We'd like to expand this to include vegetarian and vegan options. The label could sound something like "Allergier / Ideologiske preferanser (f.eks. vegetar)"

**Comment by mariusaarsnes** [comment]
Can this also be expanded to highlight that it is *food* allergies/preferences?

Alternatively splitting it into two fields: one for food allergies and one for other allergies.

We experience people writing allergies such as "dust" or "cats" which is not relevant for the committees using this information, and honestly annoying to filter through (both other legit allergies and bullshit...) when sending a list of allergies to restaurants etc.
