### ISSUE TITLE
Rename develop to master

### ISSUE THREAD

**Issue by plusk** [dotkom/onlineweb4#2321]
This is the only repository in the only student organization in the god damn world that uses "develop" instead of the default name "master". It is hella confusing for _everyone_. and it messes with my aliases.

**Comment by FluidSense** [comment]
```
git branch -m master newname
git push origin newname
# Change "Default Branch" in settings/options in GitHub
git push origin :master
```
Men må sjekke hvilke ting det brekker i tillegg

**Comment by henrikhorluck** [comment]
Suggestion: We wait until Github releases seamless™️ default branch renaming, and then renames it to main to go with the flow as well? https://github.com/github/renaming

**Comment by henrikhorluck** [comment]
It has been done.
