### ISSUE TITLE
OW doesnt support use of employee mails

### ISSUE THREAD

**Issue by kharann** [dotkom/onlineweb4#2334]
**Describe the bug**
Apperantly OW4 doesnt support use of employee mails, which means the user has issues with verifying their membership if their main email is their employee mail

**Expected behavior**
An user should be able to verify their membership and use OW as long as they are a student too.

**Comment by FluidSense** [comment]
Student name is automatically retrieved from Feide, and it on employees, it is set to "firstname.lastname". 
Seemingly, by changing scope to 
`scope: userid-feide` we can get the correct username

**Comment by FluidSense** [comment]
https://github.com/dotkom/onlineweb4/blob/develop/apps/dataporten/views.py
`ntnu_username_dataporten = userinfo.get('email').split('@')[0]`
I believe this needs to be changed after adding the `userid-feide` scope to not get email, but rather the approriate field.
