### ISSUE TITLE
Add photo consent to events

### ISSUE THREAD

**Issue by oleast** [dotkom/onlineweb4#2339]
**Is your feature request related to a problem? Please describe.**
Users should be allowed to specify if they allow the event hosts to take pictures of them and post them after the event.

**Describe the solution you'd like**
The user should somehow be able to give consent when registering.

**Describe alternatives you've considered**
The users could be able to set a global setting for photo consent.
The setting could also be used as a default for the other (preferred) solution.

**Additional context**
Privacy and GDPR and all of that

**Comment by Chaaarles** [comment]
Epic fix
