### ISSUE TITLE
Receipts are sent multiple times for individual transactions

### ISSUE THREAD

**Issue by torjusti** [dotkom/onlineweb4#2348]
**Describe the bug**

Receipts are mailed multiple times, even though only one payment occurs. The receipts have differing IDs.

**To Reproduce**

- Purchase something in the webshop, and observe that two receipt mails are received.
- Add money to your wallet for the same behavior.

Probably also occurs when paying for events.

**Additional context**

My guess, I haven't checked that this is precisely the case: Receipts are sent when PaymentRelation objects are saved. Following the recent changes to payments using Stripe, payments get saved multiple times. Perhaps getting asked for 3D-Secure authentication results in a third mail?

**Comment by oleast** [comment]
I would suggest this stems from the receipts being created every time a transaction/relation is saved.
Receipts should rather be created when the transaction or relation changes updates status from `SUCCEEDED` and `REFUNDED`, as those are the only appropriate times to send them.

**Comment by torjusti** [comment]
I don't think we send receipts for refunds? It's probably something we want, but it might belong in another issue entirely.
