### ISSUE TITLE
Show/Store gender of event participants

### ISSUE THREAD

**Issue by petterroea** [dotkom/onlineweb4#2377]
**Is your feature request related to a problem? Please describe.**
For the excursion, we need the legal gender of the participants. While this is something we can collect with a google form, i did not think about this, and i expect this to be a mistake that later leaders will make.

Therefore, i think it would be nice with a feature in onlineweb that collects and shows the legal gender of event participants, if neccecary.

**Describe the solution you'd like**
It could be implemented as an optional user field called "Legal gender", and the ability to force people to set it before signing up to an event.

**Describe alternatives you've considered**
Google forms is an alternative, but as said earlier, i think its easy to assume this information will be available about the participants who signed up.

**Comment by FluidSense** [comment]
I believe this is tightly coupled with international travels, but if there are other use cases where we are legally obliged to gather legal genders, feel free to reopen and suggest them!

If this is not a field which is needed for more than international travels, I would suggest this to be solved through the event extras feature.
