### ISSUE TITLE
Add filtering by payment description to paymentrelation in admin

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb4#2399]
**Is your feature request related to a problem? Please describe.**
If you want to verify the payment timestamps and people, it is very helpful to be able to filter by all payment relations related to i.e. an event with the name "Julebord 2019"

**Describe the solution you'd like**
The text you fill in the search-field filters based on the related payment's description

**Additional context**
Mostly helpful for the case of "Julebord 2019", where we had to refund most of the attendees, due to reduced price

**Comment by oleast** [comment]
This proves to be kinda impossible to actually implement.

Since the related model is generic we cannot filter on a specific database column, which we need in order to use the admin search.
