### ISSUE TITLE
Fix background color for on Splash for smaller (mobile) displays

### ISSUE THREAD

**Issue by mariusaarsnes** [dotkom/onlineweb4#2498]
**Is your feature request related to a problem? Please describe.**
The background color for the list items highlighting the different days for Fadderukene is wrong. It is still using the old (?) Online-blue

**Describe the solution you'd like**
Change the background color for these items to be the same as the rest of the page.

**Additional context**

![image](https://user-images.githubusercontent.com/15379456/89176194-6631d880-d589-11ea-9421-0ec7b3b954fa.png)

**Comment by CarlOfHoly** [comment]
I think this might be displaced. I created a new issue and PR in glowing-fortnight where the splash is hosted.

https://github.com/dotkom/glowing-fortnight/pull/72

**Comment by henrikhorluck** [comment]
🎉🎉🎉
