### ISSUE TITLE
Updating "opptaksperiode" throws error in dashboard 

### ISSUE THREAD

**Issue by monikahm** [dotkom/onlineweb4#2501]
**Describe the bug**
Trying to save changes on "opptaksperiode" throws "Opptaksperioder kan ikke overlappe med hverandre".

**To Reproduce**
1. Go to 'dashboard -> komitesøknader -> se opptaksperioder'
2. Click on any application period -> edit -> (eventually change commitee) -> save
3. See error

**Expected behavior**
Updating event even if nothing is changed

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Chrome
 - Version 84.0.4147.105

**Additional context**
It works to update application period in administration panel

**Comment by henrikhorluck** [comment]
Fixed in #2504
