### ISSUE TITLE
Most notifications are not sent to their recipients

### ISSUE THREAD

**Issue by oleast** [dotkom/onlineweb4#2526]
Most notifications are left as not sent to their users, which means users may not receive payment reminders and other important information.

Error event in Sentry:
https://sentry.io/organizations/dotkom/issues/1885443442/events/?project=204971

Lift of notifications where you can see what has not been sent:
https://online.ntnu.no/admin/notifications/notification/?p=17

**Comment by FluidSense** [comment]
Mails are now fixed! Push notifications still remain a mystery.

**Comment by oleast** [comment]
For the actual problem this issue referenced, this has been fixed now. Right @FluidSense ?

**Comment by FluidSense** [comment]
Seemingly!
