### ISSUE TITLE
Removing feedback from events does not work for some users. 

### ISSUE THREAD

**Issue by tokongs** [dotkom/onlineweb4#2573]
**Describe the bug**
When trying to remove feedback relations from an event some users experience an unhandled exception of type WrongAppError coming from django guardian. 

**To Reproduce**
1. Go to an existing event in the dashboard
2. Click on"fjern" on the feedback
3. wooow

**Expected behavior**
The feedback should be removed or a message should pop up if not allowed. 

**Additional context**
Sentry Issue: [ONLINEWEB-4-1EW](https://sentry.io/organizations/dotkom/issues/1900539057/?referrer=github_integration)

**Comment by FluidSense** [comment]
Possibly related to #2572
