### ISSUE TITLE
Update JWKS with a modulus length >= 2048 bits

### ISSUE THREAD

**Issue by haakonjacobsen** [dotkom/onlineweb4#2982]
**Describe the bug**
The recommended modulus length is 2048 bits for jwks. Online uses 1024 which will break the minimum required length in a lot of libraries when verifying idTokens.

**To Reproduce**
1. Go to https://old.online.ntnu.no/openid/jwks
2. Look at the "n" attribute value. 
3. Check the length of the value
4. Confirm it is too short.

**Expected behaviour**
I expect the public key to follow the minimum requirement for jkw modulus length of 2048 bits.

**Screenshots**
<img width="1643" alt="jwks" src="https://user-images.githubusercontent.com/15661593/214597984-3cd6db06-289b-4ecd-94f8-60069a4e203d.png">

**Additional context**
Without this change, it is more difficult or (maybe) sometimes impossible to use third party authentication libraries, as we do not adhere to the JWK/JWA standards.

For more information see [RFC7518](https://datatracker.ietf.org/doc/rfc7518/) section 3.3. Since Online uses RS256:

"A key of size 2048 bits or larger MUST be used with these algorithms."

**Comment by AndreasWintherMoen** [comment]
Yep. Using [jose](https://www.npmjs.com/package/jose) to verify JWTs issued by OW fails because of this issue. Error says: _RS256 modulusLength 2048 bits or larger_.
