### ISSUE TITLE
Favicons should be properly implemented

### ISSUE THREAD

**Issue by hernil** [dotKom/onlineweb4#387]
Some superficial research revealed that favicons is not what it once was. There are, for example, now different implementations for creating proper mobile shortcuts on the home screen and some special cases for implementing them in IEx. 

We have basic support for most browsers and also Apple devices, but this should be extended.

**Comment by hernil** [comment]
Could probably just run the logo through something like [this](http://realfavicongenerator.net/) and be done with it.

**Comment by nixolas1** [comment]
try this! http://realfavicongenerator.net

**Comment by sklirg** [comment]
This should have been fixed.
