### ISSUE TITLE
Feedback views can't use @staff_member_required

### ISSUE THREAD

**Issue by melwil** [dotKom/onlineweb4#686]
We are taking away staff priovileges from other comittees than dotKom when the dashboard gets made, which makes these checks in feedback irrelevant. 

I suggest you make your own decorator here, where you validate whether or not the user is in a comittee that should be able to see feedbacks.

I don't know if we should allow dotKom and/or HS as well? Thoughts?

**Comment by sklirg** [comment]
Could also be implemented using django-guardian for object level permissions. https://github.com/dotKom/onlineweb4/blob/23e6e704665d9135ef385377702000bc3634c444/apps/posters/dashboard/views.py#L171
