### ISSUE TITLE
Hold new users hand when registering new users

### ISSUE THREAD

**Issue by hernil** [dotkom/onlineweb4#866]
Det er viktig å huske at brukeren er dum. - Asbjørn Fellinghaug, tidligere leder.

Mange brukere skjønner ikke at de skal validere stud-epost for å bli medlemmer. Forslag: 

Når man validerer eposten sin (som ikke er stud-mailen) og man logger inn for første gang får man et spørsmål om man er Onliner/informatiker eller gjest. Førstnevnte får mulighet til å skrive inn stud-epost direkte der. Case: førsteklassinger registrerer konto før de vet ntnu-brukernavnet sitt. Da kan de be om å få påminnelse om en uke. 

Forslag 2: Alle som er gjest per idag endres til en "undicided" gruppe og når man går på OW4 så får man en prompt "er du onliner eller gjest?" man velger og får mulighet til å skrive inn ntnu-eposten sin hvis man er onliner. Bam. Done deal. Denne promten nagger som morra du når du ikke har rydda rommet med mindre du har valgt en av delene.

**Comment by plusk** [comment]
This is a really really really big issue which we've talked a lot about over the past few years. We will handle it one day, but we're moving the issue to OWF.
