### ISSUE TITLE
Feedback - Graphs on small screens

### ISSUE THREAD

**Issue by Torrib** [dotKom/onlineweb4#978]
Pie charts looks like crap on mobile devices when there are to many alternatives.
The legend takes up a lot(all) of the space.

**Comment by hernil** [comment]
Is this actually something that is viewed in mobile screens or should we follow the logic of dashboard where it's functional but not optimal?

**Comment by Torrib** [comment]
It's been a long time since i looked at this and it's a bit tricky.
I don't know how the companies use it though.

**Comment by hernil** [comment]
I've sendt an email to bed- and fagkom for input.

**Comment by hakloev** [comment]
We in fagKom discussed this during our meeting today, and we see no point in you implementing this functionality. We've not gotten any feedback from companies regarding how the graphs looks on mobile screens. We think most of the companies look at this using desktop computers.

**Comment by OptimusCrime** [comment]
@hakloev fagKom gives green light to close this?

**Comment by hakloev** [comment]
Yes, that were our conclusion.
